### ISSUE TITLE
Can't add extra accounts

### ISSUE THREAD

**Issue by Nosferatu1922** [PokeAlert/PokeAlert#1]
Trying to add extra accounts. Getting error:

"The username or password are not valid (or PokemonGo servers are down?)"

I tried several accounts, all log in to PTC website fine, Log in to the actual game fine. But still can't add.

Also tried turning notifications off and force stopping the app and restarting.

**Comment by Nosferatu1922** [comment]
Rebooting the entire device allowed me to add 3 accounts before getting the error again. So perhaps a service is still running that prevents adding accounts.

**Comment by ferbeb** [comment]
Disabling the background service fixed the problem for me, was able to add more than 5 accounts at once.
