### ISSUE TITLE
Multiple Notifications for same Pokémon

### ISSUE THREAD

**Issue by fbreunin** [PokeAlert/PokeAlert#10]
Since version 2.2.2, I get multiple notifications for the identical Pokémon (same location and despawn time), in intervals of a few minutes. Looks like I get a notification when the same spot is revisited by the search, independent of whether the Pokémon is newly discovered or was found before by the search. This issue did not exist in 2.2.1!

**Comment by bungral** [comment]
Getting the same issue and with multiple accounts they are pinging pretty frequently!

**Comment by fbreunin** [comment]
Seems to be fixed in 2.2.3, thank you very much!
