### ISSUE TITLE
No notification sound after update

### ISSUE THREAD

**Issue by RadziQ** [PokeAlert/PokeAlert#105]
Hey. As title says, no sound for notifications after update. Tried changing every option (default / none), custom off and on and doesn't work.
Btw thanks for your work, really appreciate it.

**Comment by PokeAlert** [comment]
Hey, You need to select a VALID sound from the "use custom notification" sound.
(forget the "Use pokeAlert" it's a mistake from me I forgot to remove that option)

Now if you selected a VALID sound (mp3, ogg, etc..) it will be selected and played. if for some reasons there is a error to use these sound the default will be used.

Can you try select a sound and restart the app ? (even though you don't need to restart)

**Comment by damnitimlost** [comment]
I actually kinda liked your custum PokeAlert sound. Where can we can find it?

**Comment by PokeAlert** [comment]
https://notificationsounds.com/wake-up-tones/soft-bells-495

**Comment by WingChroniam** [comment]
Hey I hope I'm not asking too much for this, but is it possible for you to set it up so we get different notification sound for specific Pokemon? For example this could be controlled from the Notification Filtler by using 2 columns for check marks. First column for uncommon (Charmander) then second column for like super rare (Snorlax). Sometimes there are Pokemon you definitely care and what to know are spawning, but not willing to go out of the way to catch, unless of course if it's a Snorlax or Lapras you know?

**Comment by PokeAlert** [comment]
I'm rewriting a new Filter with multiple filter (Called 'profiles') and you will be allowed to do exactly what you asked.

it is in development now probably will be released in in these following days

**Comment by WingChroniam** [comment]
YES! Thank you so much. I appreciate this beautiful App :)

**Comment by RadziQ** [comment]
Well, I am using Nox to scan when I am using my notebook and here I cannot change ringtone (in Nox and PokeAlert settings). I guess PokeAlert used notification sound previously (because that is the sound I see in nox settings for notifications and heard if PokeAlert found something) and now it's using ringtone sound?
