### ISSUE TITLE
Remove "PokeAlert service is running"?

### ISSUE THREAD

**Issue by jagauthier** [PokeAlert/PokeAlert#113]
I am using an application called "Fit Notifications" that forwards notifications to my FitBit Surge.  However, this app seems to notify every 30(?) seconds or so that it is running.  Which makes this functionality somewhat useless.  Could that notification be suppressed?

**Comment by PokeAlert** [comment]
Unfortunately It needs to be kept there otherwise Android will wipe the service whenever he wants

**Comment by jagauthier** [comment]
Hm, interesting.  I was using another app before this called "PokeDetector".  It has an option to disable the notification. Maybe the difference is that is not running as a service?  I'm not completely sure I understand the specifics with Android applications.  Maybe this makes sense to you:
http://stackoverflow.com/questions/28255276/keep-service-running-in-background-without-showing-notification

**Comment by PokeAlert** [comment]
Yep, that is the reason why I need that to be 98% sure android wont kill it.
the link you post works great for new Android version. and not soo great for for android 5
