### ISSUE TITLE
All my accounts were banned in new update (2.3.13-4) 

### ISSUE THREAD

**Issue by BenceCsonka** [PokeAlert/PokeAlert#120]
After update all my accounts were marked as banned, so the scan process stopped and couldnt find any pokemon. So i installed back 2.3.13-3, and everything is allright again, all my accounts are alive.

**Comment by PokeAlert** [comment]
There is a bug where if the app loses internet all the accounts get marked as banned. Quick fox for this is to remve your account and put them back (OR if you had them saved in a file simply press the load icon in the account settings)

2.3.13-5 is gonna be pushed soon and fixes this.
