### ISSUE TITLE
How can I contact you?

### ISSUE THREAD

**Issue by shadowholic** [PokeAlert/PokeAlert#123]
My app keep crashing 2 times out of 3. I have around 100 account. Please let me know how I can send you my log. I want you to take a quick look at it. 

Please let me know.

Thanks and keep the good work! Love what you've been doing so far! Always new updates.

A

**Comment by PokeAlert** [comment]
Hey, please send me the log to pokealertapp.help@gmail.com. 
I might were the crash comes from I will give you an apk that have my fixe (i cannot test it because I dont have 100 account)

**Comment by PokeAlert** [comment]
Issue "kind of solved" op is using android 4.4.2 which is crashing after sometimes (only happens on 4.4.2)

**Comment by shadowholic** [comment]
Sounds good please take a look at the other Issues/Suggestions i listed on
GitHub.

Thanks

Alex
