### ISSUE TITLE
Overlay button blocks north button

### ISSUE THREAD

**Issue by newscientist101** [PokeAlert/PokeAlert#132]
If you rotate the map a button to return north to the top of the screen appears. This is blocked by the overlay button.
![image](https://cloud.githubusercontent.com/assets/12604436/18484530/754b9e22-79ae-11e6-8569-31fd941a21c4.png)

**Comment by PokeAlert** [comment]
How did you manage to rotate? I have set "portrait only" for the map :O

**Comment by newscientist101** [comment]
Map rotation has nothing to do with screen orientation as far as I know. The gesture is the same as any app that uses Google Maps, two fingers rotated around a central point.

**Comment by jagauthier** [comment]
I was able to reproduce this by pinching and spinning the map with my fingers.

**Comment by PokeAlert** [comment]
aaaah my bad thought it was screen rotation

**Comment by WingChroniam** [comment]
Oh yeah this is very true. If you could move it slightly away xD
