### ISSUE TITLE
Lock icon doesn't unlock

### ISSUE THREAD

**Issue by baldypal** [PokeAlert/PokeAlert#136]
In the recent update when you brought the lock icon back, it doesn't change into an unlock icon nor does it unlock when you press it again.

**Comment by PokeAlert** [comment]
This is the intended purpose to keep consistency. If you want to remove the area simply "tap" once on the circle.

**Comment by baldypal** [comment]
Tapping the circle doesn't unlock the area either though. It just shows a
red error at the bottom "stop the service before editing an area". I tried
that too from previous change.

Adam Jones

**Comment by jagauthier** [comment]
I am experiencing this as well, and I'm not entirely certain if its use is unclear or the program is not behaving correctly.

**Comment by PokeAlert** [comment]
@baldypal Are you trying to remove the circle while a scan is going?

**Comment by baldypal** [comment]
If a scan is running when background services are running, then yes. I did
not do a manual scan by pressing play button at bottom. If I just
accidentally lock am area, I have to stop background services, touch blue
circle, then start background services again. When I used to just touch the
lock again.

Adam Jones

**Comment by PokeAlert** [comment]
Ok good, I will fix the "impossible to remove" while scanning. That is a a bug introduce with the multiscan

**Comment by Eric678** [comment]
If you are not using advanced assignment of account to areas then touching the blue circle immediately unlocks which is a real PITA - constantly doing this by mistake when dismissing a mon popup.   Please take more time to consider the effect of changes you make!  Thanks.

**Comment by PokeAlert** [comment]
This has changed in 2.3.14-7. area are not unlocked directly to avoid mistakes
