### ISSUE TITLE
accounts not working?

### ISSUE THREAD

**Issue by kennyisme01** [PokeAlert/PokeAlert#137]
my account not working halfway through scanning but not shown banned

**Comment by PokeAlert** [comment]
Will need more info on this. Manual scan? How many account? Fix area ?

**Comment by JayyAyy** [comment]
I'm getting the same. My accounts stopped working while in a background scan. I removed one to try and re-add it but it won't let me. I tried a manual scan and it showed some pokemon then stopped and said the accounts didn't work again. The manage account page shows all my accounts are green and it did show some pokemon during the manual scan before stopped so I'm just assuming they're not banned.

**Comment by PokeAlert** [comment]
The message is miss leading. I'm showing the same message "You account x doesn't seem to work anymore" when they cannot login for some reason and/or banned

So if you see them green it means it just failed to login (maybe to much login attempt?)

**Comment by PokeAlert** [comment]
Message clearer in 2.3.14-5
