### ISSUE TITLE
App keeps crashing randomly

### ISSUE THREAD

**Issue by seonghoon85** [PokeAlert/PokeAlert#140]
Hello PokeAlert dev,

My app keeps crashing after 4-5 consecutive scans and I'm not sure why.
The app just crashes during a scan. If I restart the app, it works fine again then it crashes after 4-5 scans.
I'm running the latest version of PokeAlert. My phone is a LG Optimus G Pro E980.
I saved a log file and attached it to see if that will help at all. It is attached.
Thanks for your help!

[logcat_1473889498960[1].txt](https://github.com/PokeAlert/PokeAlert/files/474811/logcat_1473889498960.1.txt)

**Comment by PokeAlert** [comment]
Hey,

How many accounts are you using? Did it crash as well with the previous version(s) ?

**Comment by seonghoon85** [comment]
Hello,

My Android version is 4.4.2 and I'm using around 50 accounts.
It crashed with previous versions as well so I decided to upgrade to the latest version and it still keeps crashing.
Thanks for your help.

**Comment by PokeAlert** [comment]
Yep this is the problem right there. Android 4.4.2. There is a problem with 4.4.2 and memory usage.  I don't have this device so I cannot debug (it works with emulator) 

Could you try running this:

https://github.com/PokeAlert/PokeAlert/releases/download/2.3.13/PokeAlert_2.3.14-1_leak.apk

It the same as 2.3.14-1 but with an attempt to reduce memory usage. Could you tell me if you still see the crashes ?
