### ISSUE TITLE
2.3.14-2 Crashing

### ISSUE THREAD

**Issue by Jruby6699** [PokeAlert/PokeAlert#141]
As soon as the app opens it crashes. I am using Galaxy s7 edge. App was completely operational before this.

**Comment by jagauthier** [comment]
When I first loaded 2.3.14-2 it loaded.. but no pokemon were found.  So I restarted the app, and now I am experiencing the same issue as you.

**Comment by PokeAlert** [comment]
It's the new icons :(

**Comment by jagauthier** [comment]
Sorry man!  I know you're working hard on this!

**Comment by PokeAlert** [comment]
let me revert

**Comment by PokeAlert** [comment]
@jagauthier @Jruby6699 You might have downloaded the broken version (I had reuploaded the right one like 4 min after the update)

Can you try reinstalling again?

https://github.com/PokeAlert/PokeAlert/releases/download/2.3.14/PokeAlert_2.3.14-2.apk

**Comment by jagauthier** [comment]
Same with that one :(

**Comment by jagauthier** [comment]
Okay, I removed the app. Reinstalled the -2 apk and I can see the new icons.
There must be some resource holding things up with the upgrade.

**Comment by PokeAlert** [comment]
Sorry about that :/

https://github.com/PokeAlert/PokeAlert/releases/download/2.3.14/PokeAlert_2.3.14-3.apk

**Comment by Jruby6699** [comment]
Downloaded from the link you supplied and it is still crashing immediately when opened.

**Comment by Jruby6699** [comment]
Had to uninstall and reinstall to get it to work. I was hoping I wouldn't have to add all 20+ of my accounts but oh well, atleast it's working :) 
Amazing job on this app by the way!

**Comment by jagauthier** [comment]
I removed and reinstalled -3 cleanly.  Now it appears to be okay.

Jruby: You need to save and load those from file!

**Comment by PokeAlert** [comment]
@Jruby6699 
https://github.com/PokeAlert/PokeAlert/releases/download/2.3.14/PokeAlert_2.3.14-3.apk

It really should override the previous version there is no need to remove

**Comment by jagauthier** [comment]
ugh!  I went through the work of setting all my filters....
and the app crashed. Do you think it's related to the WIP you have with the filter settings?

**Comment by PokeAlert** [comment]
Nop, code is not there. Does it crash everysingle time ??

**Comment by PokeAlert** [comment]
Can you send me the log if you can

**Comment by guigamx** [comment]
well,   worked for 10sec ,  with -3  ,   old icons, but now  its crashing right after trying to open the app

**Comment by Jruby6699** [comment]
I forgot about the accounts file! Saved me a lot of typing!

**Comment by PokeAlert** [comment]
damn!!! I found the problem

**Comment by PokeAlert** [comment]
was nothing to do with the icons

**Comment by PokeAlert** [comment]
https://github.com/PokeAlert/PokeAlert/releases/download/2.3.14/PokeAlert_2.3.14-4.apk

**Comment by guigamx** [comment]
kek , working now
but  u removed the  new icons right?

**Comment by PokeAlert** [comment]
Ill put them back then :D

**Comment by guigamx** [comment]
if dont take alot of work , u could let the option to choose :D  
personaly i like the small ones xD

**Comment by PokeAlert** [comment]
this is how the new one look
http://imgur.com/a/rkm1d

@Jruby6699 @jagauthier @guigamx 
If you dont mind testing?
https://github.com/PokeAlert/PokeAlert/releases/download/2.3.14/PokeAlert_2.3.14-4_icon.apk

**Comment by Jruby6699** [comment]
New icons are appearing on the map with the icon apk you supplied. Works fine for me!

**Comment by PokeAlert** [comment]
@Jruby6699 Will put a switch as you suggested
