### ISSUE TITLE
Unlock location issues

### ISSUE THREAD

**Issue by Ayron88** [PokeAlert/PokeAlert#144]
Since update not able to unlock the location I have selected unless I completely close the application. The multiple area selection is great as well but can't unlock the areas nor the accounts.

**Comment by PokeAlert** [comment]
I need more info. It works as expected when I try.

How are you unlocking an area ? Is there any error message? Multi-scan or single scan? etc...

**Comment by Ayron88** [comment]
I figured it out, I didn't know it was changed to click the blue Circle instead of the lock
