### ISSUE TITLE
Am I the only one who liked the old icons better? 

### ISSUE THREAD

**Issue by fooentes** [PokeAlert/PokeAlert#146]

**Comment by halloonyc** [comment]
hehe, I like the higher res ones to be honest. the old icons were a little hard to make out sometimes. The difference between a dratini and a dragonair looked pretty similar.

**Comment by Solarisphere** [comment]
Yeah I definitely preferred the old ones. These ones are huge and are constantly overlapping each other, in addition to being ugly. They have a bit of a yellow tint to them.

**Comment by Eric678** [comment]
Love the new icons! Thanks! Those with old tech low res screens are the ones complaining so I guess there is a problem for them - perhaps provide 2 apks (or settings switch) till it is sorted.

**Comment by PokeAlert** [comment]
I can't provide 2 apk unfortunately  but I can provide a "choice" in the settings.
But before doing this I need to add some more logic to scale the bitmap for the right screen (I had hard coded it to 100x100 thinking it would be enough for everyone)
