### ISSUE TITLE
New icons are way too large

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#147]
Hi, @PokeAlert I have noticed that you changed the icons and they are very big if the map is zoomed out. With the old icons i was able to see everything on the zoomed out map, now I have to zoom in a lot to be able to see everything clearly. You should add the option to select the icon size in the settings because for some people it is good but for some not - it depends on phone screen resolution.
![screenshot_2016-09-16-03-48-01](https://cloud.githubusercontent.com/assets/12085708/18572117/e77e6fec-7bc0-11e6-8e87-59a1479ccd23.png)

**Comment by evilcreature2003** [comment]
Yes, too large for smaller phones. Please revert to old icons.

**Comment by PokeAlert** [comment]
done. Though I'd like to work a bit more on this and find a way to make the bitmap scalable whatever the screen side the use have.

@evilcreature2003 @TFD777 what phone model and screen size do you guys have?
