### ISSUE TITLE
Use Map Scan Filter even when Notification scanning

### ISSUE THREAD

**Issue by ObviousLeeGitHub** [PokeAlert/PokeAlert#15]
As of now, when you are notification scanning in the background, only the Pokemon you checked in Notification Filter will show on the map. I think it would be an improvement to still show the Pokemon of the Map Scan Filter on the map even while notification scanning. Only using the notification filter for notifications. That would be awesome :)

**Comment by Natzely** [comment]
I'd like this as well. Sometimes I don't find any poke in my notification filter and I wonder if the scanner is working. I'd still like to know where _all_ the poke are, but only be notified when a poke in my notification filter shows up.

**Comment by TheRadGasm** [comment]
Agree. I think this is a bug, since all the 'mons showed up on the map before v2.8.
Please fix!
Pokemon that aren't search filtered should still be on the map!

**Comment by PokeAlert** [comment]
Right Right Righttttttt. "I" personally (and this is why I it worked in the earlier version) like to have all to pokemon check on the Notification Filter on the map **regardless** of the Map Filter

But apparently there was quite some people where it was bothering them that pokemon where showing even though they didn't check it in the Map Filter

I think I (we) will have to rethink how we can make these filters work to accommodate the both type of people.

**Comment by voythas** [comment]
@PokeAlert I think it could be done combaining those two dialogs into one, here's quick mockup I did (actually two versions of it):
![pokealert_0a](https://cloud.githubusercontent.com/assets/681416/17781547/f8adff74-656f-11e6-90ae-a85ad85262c4.png)
![pokealert_0b](https://cloud.githubusercontent.com/assets/681416/17781548/f8af78d6-656f-11e6-88be-63d04e2a6ad3.png)

**Comment by Natzely** [comment]
This actually a very neat idea.
