### ISSUE TITLE
Please help me with background scanning

### ISSUE THREAD

**Issue by davidc1223** [PokeAlert/PokeAlert#151]
First I'd like to thank you for the awesome app, it's been one of my go-to scanning services. It's very handy indeed, but I have an issue I hope can be helped.

I've been trying for awhile to get PokeAlert to do background scanning, while the phone is idle or while I'm in the Pokemon Go app, to no avail. It seems that I'm even having trouble doing background scanning in overlay mode, as well. I'm guessing it is something simple that I am missing to make this work, and I have looked through this forum and other forums for remedies to my problem. 

The red circles seem to be moving around while the app is in the background, but for whatever reason they just don't find Pokemon. 

I'm using a Samsung Galaxy S6 Active
Android version 6.0.1

Thanks again!

**Comment by halloonyc** [comment]
did you check your Map filter? if you have nothing selected, you will see nothing.

**Comment by PokeAlert** [comment]
does it work when you do a manual scan? You see the red circlemoving and pokemon showing up ?

**Comment by davidc1223** [comment]
Thanks for the replies! Since my post yesterday, I have discovered that it seems to selectively work. I have been doing a lot of experimenting, and I actually did get it to work a little bit yesterday, but it's just not reliable. It works like a charm if I leave the app in the foreground for background scanning, and don't let the Androids screen shut off. To answer both your questions, yes my map filter has Pokemon selected and yes, manual scans work fantastic. Red circles moving and Pokemon showing up.

**Comment by PokeAlert** [comment]
Is there any app on your phone that is preventive the background service to work? (some kind of antovirus etc.. ?)

**Comment by davidc1223** [comment]
You know, it might be as simple as me running my phone in power saving mode. I've been obsessive about saving battery and that limits device performance, including the RAM which could be the whole issue all along. I turned it off and things seem to be going smoothly for now. I'll say something if it stops working, but I think this is the solution. Again, thanks for your response!

**Comment by WingChroniam** [comment]
Did you at least get that account going in the game? Like catch a Pokemon and get a nickname going?

**Comment by PokeAlert** [comment]
@davidc1223 There is indeed a problem when the app is in saving mode, requests doens't go through completely.
Can you try without it for a while?

**Comment by davidc1223** [comment]
Yes, I've switched to no power saving mode. I have a new 30,000 mAH battery to use so power is no longer an issue for me. This seems to have resolved my problem, everything is working great now. Sorry for creating a thread over something so simple to find out on my own. XD

Thanks very much!
