### ISSUE TITLE
Background scan doesn't work on emulator android 5.1.1 api 22. Single scan work fine.

### ISSUE THREAD

**Issue by Dragonboh** [PokeAlert/PokeAlert#157]
Background scan doesn't work on emulator android 5.1.1 api 22. Single scan work fine. No pokemon on map, no notifications. But sing scan work fine. Where do u test application? Maybe i am doing somthing wrong

**Comment by PokeAlert** [comment]
You need to enable the location on your emulator for the background to work

**Comment by Dragonboh** [comment]
i am using fixed map position, and location is on
