### ISSUE TITLE
Android 7.0 Nougat support

### ISSUE THREAD

**Issue by Gelob** [PokeAlert/PokeAlert#158]
I have a Nexus 6P and recently the update was pushed to Nougat and since then any of the updates from Pokealert won't install and just crash when trying to install them.

**Comment by PokeAlert** [comment]
ooh. Does it crash "during" the install ? or when you start the app ?

**Comment by newscientist101** [comment]
The package installer still crashes for me with Nougat and 2.3.15

**Comment by Gelob** [comment]
Same for me when trying to install 2.3.15, it crashes during the install.

**Comment by newscientist101** [comment]
For the first time since updating to Nougat, the update (for 2.3.16-1) completed successfully.
