### ISSUE TITLE
Suggestions/Requests (scanning/IV/locations/mapfollow)

### ISSUE THREAD

**Issue by D3miS3raph** [PokeAlert/PokeAlert#159]
1 : A huge thing that would be great is as driving or walking or riding around it would be great to see the map recenter when it starts it's next scan cycle rather than having to manually push the button.  Allow for it to automatically center back on your location by emulating that button press at the beginning of each new scan cycle. (toggle option so that people can choose to do this when plugged into power)

2 : Unlock location scan to go back to follow mode.  Old version let you push lock to unlock, now it seems that it only locks and you have to close app (or there is another way that I'm missing?)

3 : I don't like some of what pokemesh does but it has done a few good things.  It shows you pokestops and lured pokestops.  It also shows you gyms and the color of the gym and the defender.  And now you can also click on a pokemon and it will show you the moves and IV values of that pokemon.  These would be great features here.  Also their 3d official graphics look quite nice.

4 : Alerts.  It would be great to set a custom sound or alert for certain pokemon that are even more important to find.  For example I would like to set a unique sound or vibrate when a blastoise or alakazam pops up, but just a normal alert for ghastly that I need, and then no alert for things like weedle.

That's it!  For me those things would make this app even more perfect.  And for the record I love it and it works amazingly well!  And the notifications etc are awesome.  A random cool feature (harder I'm sure) but if we wanted to track spawns in an area over time it would be cool to allow the app to write the time and location of pokemon to a log csv file we can look at on a pc later and try to see when rares and where other pokemon spawn :)

Keep up the great work!
D3miS3raph

**Comment by PokeAlert** [comment]
1) I note this down thanks!

2) Yes you can, to unlock an area simply tap on the blue circle and unselect ALL the accounts ;)

3) Yep this is coming right after this
https://twitter.com/PokemonGORadar1/status/778288863362027520

4) And that is ALREADY possible
https://github.com/PokeAlert/PokeAlert/issues/155

Thanks!

**Comment by D3miS3raph** [comment]
You are awesome!
