### ISSUE TITLE
There is a word "fast" next to each fast attack

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#164]
Just noticed this and I think this was unintended.
![screenshot_2016-09-22-05-23-46](https://cloud.githubusercontent.com/assets/12085708/18735248/2320018c-8085-11e6-9ff8-41c853e12f31.png)

**Comment by PokeAlert** [comment]
That is the move name I receieve from the server don't it can be "tackle" or "tackle fast" not sure whats the dif
