### ISSUE TITLE
Pokealert not actually running in the background

### ISSUE THREAD

**Issue by angrymarker** [PokeAlert/PokeAlert#166]
I launch the app (Galaxy note 4), zoom in on my position with the gps button, and click the background button. I get notified of every pokemon on the map, so I click home, and open up pokemon go, and put it in the battery saving position. After 3 hours, I do not get a single notification, though I am catching multiple pokemon in Go. Notification filter is set to notify of all. If i open up pokealert again, it notifies me of all the ones in the area.

Worked perfectly until the overlay was implemented.

**Comment by jagauthier** [comment]
The overlay doesn't work very well for me.  I just keep the app in the background.

**Comment by RadziQ** [comment]
Yeah, for me overlay is a bit laggy and disappear after a while during playing PoGo. Maybe too slow phone (Samsung S4) or phone saving battery mode.

**Comment by angrymarker** [comment]
actually, you're right RadziQ. It's because i'm in battery saving mode. Thanks!
