### ISSUE TITLE
Bug : filters dont save

### ISSUE THREAD

**Issue by D3miS3raph** [PokeAlert/PokeAlert#168]
Pulled old filter
Created new filter
Edit and it reset all changes to 151 active...
Cant use app now until fixed sadly ...

**Comment by Eric678** [comment]
+1

**Comment by baldypal** [comment]
Confirming same results with my filters.

**Comment by D3miS3raph** [comment]
Twmporary workaround.  Make filter. Edit. Click unselect all.  Select just one guys boxes. Save.  Then start selection of more and save and they saved.

**Comment by baldypal** [comment]
This work around works, though very tedious.

Adam Jones

**Comment by Eric678** [comment]
Yes it seems anything after a new filter start OR "Select all" leaves all mons ON.  Unselect all works and then you have to select what you want (don't need to save after the 1st) then save works.

**Comment by D3miS3raph** [comment]
I just got a redownload of the release notification and a new filter saved correctly

**Comment by PokeAlert** [comment]
sorry no idea what happend :/ I had a working version on my phone and pushed an wrong apk
