### ISSUE TITLE
Red scan circles not disappearing

### ISSUE THREAD

**Issue by baldypal** [PokeAlert/PokeAlert#169]
The red scan circles are not disappearing.

**Comment by D3miS3raph** [comment]
Disappearing for me.

**Comment by baldypal** [comment]
I force closes the app, log out then back in. They disappear now.

Adam Jones

**Comment by PokeAlert** [comment]
Need to check on that you are not the first mentioning this :(

**Comment by baldypal** [comment]
Happening again

Adam Jones
