### ISSUE TITLE
[Suggestions] Multiple features for filters/scan areas

### ISSUE THREAD

**Issue by TheDollarBill** [PokeAlert/PokeAlert#171]
Here are several suggestions that I'm interested in and I hope that @PokeAlert considers :). 

- A feature which would allow me to **edit multiple Pokemon profiles at once** (such as apply a notification sound and IV settings to a selected list of Pokemon), instead of opening every single Pokemon profile and editing it for every single Pokemon.
- Create a **copy of a filter** (in that same menu with "Activate", "Edit", and "Delete").
- A **confirmation message for deleting filters** (Tapping "Delete" instantly deletes the filter and sometimes I tap on it on accident).
- **Changing the "Only show if IV bigger than __%"** to have an option to only apply to notifications and not the Pokemon on the map.
- Having a **separate "Select All" and "Deselect All"** for map and notification when selecting Pokemon in the filter.
- Options such as **"Add X number of accounts"**, **"Deselect All"**, and **"Remove Scan Area"** when **assigning accounts to scan areas.**

**Comment by PokeAlert** [comment]
You are writing point by point star I'm 'trying'  to do
The biggest problem I have its not the functionaliies themself but the damn UI! 

To all the UX expert around here. Help would be much appreciated to design the filters UI screens and flow.

**Comment by RadziQ** [comment]
Could you bring back Show IVs option for all pokemons? It takes a lot of time to select this one by one.

**Comment by PokeAlert** [comment]
Yea was gonna release temporary version today but decided to invest the time actually making a proper final UI

**Comment by fooentes** [comment]
I'm working on some screens. Hold on

**Comment by fooentes** [comment]
Ok, this is how I would do it: http://imgur.com/a/7myZX

Note: IV rules have higher priority. So, if you mark Charmander to not notify on the "Notifications Screen" but on the IV Screen you check to be notified of Charmanders over 80% IV, it notifies anyway.

**Comment by jagauthier** [comment]
I like that, it's organized fairly well.    How about when "Alert" is specified on a pokemon, we automatically select "Map." This will save us from tons of tapping.  Then the trick will be the logic in notifications versus IVs.  it's just another check that if we are scanning for IVs, and notifying, then we don't notify on map presence as well. Just one notification per 'mon.

Otherwise, this looks really good. I do like the custom notifications per pokemon. It would be fun to include some default ones in the resources..   I kind if think it would be funny to have the notifications sound "A snorlax is nearby", or "A charizard is nearby."  These would be pre-recorded, of course.  Unfortunately, language is a problem.. But you could take it so far as using a text to speech library. 
http://www.tutorialspoint.com/android/android_text_to_speech.htm because these are speech independent..  
I have no idea if this is an iphone app or not (android user obviously here)

Sorry, got on a total tangent.

**Comment by WingChroniam** [comment]
I think being able to swipe one Pokemon to another while editing IV, checkbox, notification sound would be nice.

**Comment by PokeAlert** [comment]
@fooentes thanks for this! I had actually started something "similar"
look

The filter management is similar as your

Then when you enter in a profile you have this:
http://imgur.com/a/bAVYT

explanation: You can see two tab (Page0 is Map and Page1 is Notification)
You simply select which pokemon you want to filter and there is the selectAll (which select all/nothing)

Note as well the "setting" button. that will bring you to a screen where you can
  - enable the IV scan
  - set your threshold(s?)
  - set the sounds

And... if you select MULTIPLE (there will be a checkbox on the left of the name) it will still bring you to that setting screen and the vaue will applied TO ALL the selected pokemon.

**Comment by fooentes** [comment]
Yeah. Makes sense. It's looking good, can't wait to try it

**Comment by PokeAlert** [comment]
@fooentes @TheDollarBill @RadziQ 

hey I have put a VERY beta (i really don't like these left checkbox to be honest but it was the easier way to archive the multi select :())
https://github.com/PokeAlert/PokeAlert/releases/download/2.3.12/app-lite-release.apk

Could have a play and see if it makes sense ?

**Comment by fooentes** [comment]
Hey I just tried and I think it's kinda of confusing. 
Example: After selecting All, and configuring the IV to filter only above 50% it sets all the IVs to 50%, right? But when I unclick the '' select all'' and click on a single Pokémon, it always shows bulbasaur. Seems like something is wrong. And I think you could change Bulbasaur image for something else when selecting all the Pokémons.

**Comment by Jeffau921** [comment]
@fooentes The image probably haven't been dealt with because it is a VERY beta.

Although it shows Bulbasaur for everything, the functionality actually works. It might be better to reintroduce the save/cancel buttons?

 (I'm currently filtering all pokemon to only show when they're 100%IV, as well as a few selected rares with voice recording notifications; works wonder, since the release of the filters management beta, I've caught a Lapras during early morning (which woke me up), a Snorlax, a Lapras and 2 Dragonites in the middle of work, and an Exeggutor and a Dragonite while I was really playing. Caught a 100%IV Grimer too!
All of these wouldn't happen without pokealert. I must express my sincere gratitude to the developer pokealert <3 )

**Comment by PokeAlert** [comment]
@fooentes yea dont worry the img is hardcoded 
I will clean up when I'm satisfied with filter stuff. 

What do you think if the overall usability

**Comment by PokeAlert** [comment]
I have been using the beta a little and I don't like the two tab for the filters. it doesn't make sense.

This is what I will try now:

- As usual the filter profile list
- When enter a profile, ONE single screen called Filter with a simple list of Pokemon and ONE single checkbox (called select OR no check box andjust highlight when pressed)
- naviguate to an advanced filter screen common for ALL
That screen will have

 - Show on map checkbox
 - Notify checkbox
 - Notifify if IV > % field
- Show on map if IV > % field
 - custom sound button
(and the possibiliy to add extra without have problem with screen size and having column pilling next to each other)

**Comment by PokeAlert** [comment]
@TheDollarBill @RadziQ @fooentes @jagauthier @WingChroniam

**Comment by fooentes** [comment]
Great idea. That sounds much better and less confusing. Simplicity is the key

**Comment by PokeAlert** [comment]
@TheDollarBill @RadziQ @fooentes @jagauthier @WingChroniam 
Here we go

- I have reverted back the scan code (so more intrusive error messages)
- Have implemented the new UI
https://github.com/PokeAlert/PokeAlert/releases/download/2.3.12/PokeAlert_2.3.16-beta.apk

(This is the closeset 2.3.16 will look like)

I personally like it. It still needs some UI tweeks here and there but in general I find it easy to use.
The major thing that needs a change I think is that when you enter the Filter sceen you don't know "directly" which pokemon is filtered or not. I think I will change tuis by ONLY showing in the list the filtered pokemon

**Comment by jagauthier** [comment]
Alright, I'm going to give it a spin!

**Comment by jagauthier** [comment]
I am not sure filters are saving correctly.  I have 3.  I went into "dragonite", and (as expected) everything is cleared (first run). So I select Dratini, Dragonair, and Dragonite.
![screenshot_20160925-163344](https://cloud.githubusercontent.com/assets/7101432/18818078/7ec8d8ae-833e-11e6-8f14-98f2c4c3577e.png)

When I h it the back arrow, it told me the filter was saved.
![screenshot_20160925-163350](https://cloud.githubusercontent.com/assets/7101432/18818080/87d0652a-833e-11e6-8aa4-f274c6762d26.png)

But when I went back in the filter is cleared.
![screenshot_20160925-163405](https://cloud.githubusercontent.com/assets/7101432/18818082/92b0bb20-833e-11e6-9a1a-8516dd5c39ac.png)

Also, if you select some (like the three above) and then tap into one to change it's specifics (map, notification, IVs, etc) then you go back everything previously selected is deselected.

**Comment by PokeAlert** [comment]
@jagauthier 
Yea I knew it it not clear enough. I will only display the selected pokemon inthat list
What you see is all the pokemon, the checkbox on the left is to select not filter them. Select them you will a setting icon on the right
or tap a pokemon to only modify one

**Comment by fooentes** [comment]
Just tested the new version and I liked it , it's definitely an improvement. Some possible bugs and doubts. 

1) if I check a pokémon to not notify, but write to be notified when IV over 80%. Will I be notified when it's over 80 or I need to check the notify anyway?

2) First thing I did was selecting all, marking to show on map and to scan IV (left notify unchecked). After going back and saving, all the Pokémons were marked with map, notify and IV. I had to select all again, check notify and uncheck just to save. This worked.

3)  Bug. When selecting all, the minimum value says 0%. But when editing a single Pokémon, it changes to 1%.

**Comment by PokeAlert** [comment]
1) not applicable anymore with the new UI
2) this as well
3) will fix

I have release 2.3.16-beta
https://github.com/PokeAlert/PokeAlert/releases/download/2.3.12/PokeAlert_2.3.16-beta.apk

not having the checkbox on the on the first screen is horrible as I have no idea which pokemon is filtered or not so I have done this, hope it will fit on all screen.....

https://pbs.twimg.com/media/CtRszReWcAAKMhO.jpg:large

**Comment by fooentes** [comment]
The IV check is kinda crazy. Some checks change along with the scroll. Example: check some poke IV. Scroll down,  click into another poke. Back. Scroll up. Down. Up. Down. Sometimes IV is clicked, sometimes not. Even pokes I did not checked start to toggle.

**Comment by PokeAlert** [comment]
fixed :) redownload the apk (it was happening when scrolling up and down)

**Comment by fooentes** [comment]
Yay, now it works. I like it. One tweak I would add:
If a poke has notify unchecked and you go inside it, disable the IV threshold field so people know it's because of that. Same for map.

**Comment by PokeAlert** [comment]
true

**Comment by fooentes** [comment]
Possible bug: can't stop PokeAlert service. 

Stopped service, closed the app and noticed it still running. Opened the app again, stopped it again. Closed the app. Still running.

**Comment by fooentes** [comment]
Nevermind, I got confused with 2 separate apks :) it works fine
