### ISSUE TITLE
Suggestion for scan radius between 1000 and 1600

### ISSUE THREAD

**Issue by brianlech** [PokeAlert/PokeAlert#173]
1000 to 1600 for scan radius is a huge jump, is there any way you can put a couple in between? Say 1200 and 1400?  Thanks :)

**Comment by D3miS3raph** [comment]
Or even an option to manually type in an "other" range

**Comment by PokeAlert** [comment]
The range distance is nothing else than the behive steps (1,2,3,4,5,6,7,8.9.10,15 and 20) DO you REALLy need 11 12 13 or 14 ?
