### ISSUE TITLE
Error with first scan of an area.

### ISSUE THREAD

**Issue by Ultramutant** [PokeAlert/PokeAlert#177]
I have 5 accounts and when scanning a large area the first batch always shows up having not seen anything. I made sure to wait more than 10 seconds between starting a new area and closed the app and reopened after having waited. I've tried replicating this a few times on a spawn i know is up and the first group scan won't reveal anything.

**Comment by PokeAlert** [comment]
Does it do the same on the 2 scan? (stop, wait 10 sec,  scan)?
