### ISSUE TITLE
Trying to add extra accounts crashes the app

### ISSUE THREAD

**Issue by Natzely** [PokeAlert/PokeAlert#18]
When I press the button in the drop down to add accounts, the app crashes. It pushes me out of the app, cleans the map, and restarts the scan.

*Whoops, thought the close issue button was the cancel comment button...

**Comment by MrMindtrick** [comment]
I have the same issue. Also the notification and map scan filters are missing a lot of pokemon. Good luck and keep up the great work!

**Comment by papagelos** [comment]
Same problem.

**Comment by Natzely** [comment]
It's working now!
