### ISSUE TITLE
New filters crashing app

### ISSUE THREAD

**Issue by arhi3a** [PokeAlert/PokeAlert#184]
Hi!
Yesterday i updated app to 2.3.16 now when i click on filter, app is crashing and restarts, sometimes dies totaly (http://i.imgur.com/ZXGcwbo.png).
I'm Using Note 4 with andoid  6.0.1 
very rarely i'm able to open edit/activate/delate tab there and 1 time a managed to open filter editor.
Trying to save filters to file is also crashing app

**Comment by PokeAlert** [comment]
Need a log for the stacktrace

**Comment by arhi3a** [comment]
If I open app crash it and then open it again and click save log is it going to be okay or i have to do it another way?

**Comment by PokeAlert** [comment]
Either give me your exact device model number or your bootloader version (so I can find you in the crash logs) or yes make the crash happens and directy after rather quickly open the app and save the logs

**Comment by arhi3a** [comment]
I already sent logs to pokealertapp.help@gmail.com 
I wrote there waht i did to make it. hope it will give you needed information.
Some editional info:
Phone model SM-N910C
Andoid: 6.0.1
Basband version: N910CXXU1DPC1
Kernal Version: 3.10.9-7633655 dpi@SWHD4906 #1 Wed May 11 15:19:59 KST2016
Build Number: MMB29K.N910CXXU2DPE6

**Comment by PokeAlert** [comment]
It happend to be a memory problem when displaying icon in the filter screen (only for certain type of phone). This is now fix by improving the way icon are cached/created
