### ISSUE TITLE
Unable to change app language

### ISSUE THREAD

**Issue by MinionAttack** [PokeAlert/PokeAlert#191]
Hi, I've updated PokeAlert to 2.3.17, it's on Spanish language and I can't change the language to English.

I'm going to improve the translation because some strings were translater as literal and it's wrong or bad translated, moreover there are some others than aren't translated.

By the moment, how I can change the application language?

Regards.

**Comment by PokeAlert** [comment]
If you want it in english you will need to change the language of you phone (this is how pick up the languages)
