### ISSUE TITLE
Notification when IV not scanned

### ISSUE THREAD

**Issue by RadziQ** [PokeAlert/PokeAlert#196]
Hi again.
As in the title, there are notifications for pokemons that dont have IV scanned (unfortunatelly not every one has IV scanned, no information that IV scan failed). Is there possibility to do something with this?

**Comment by PokeAlert** [comment]
Which version are you on? Also note that pokemon found with FastActivated **will not have any IV**

Next version will have extra filter to let the user chose what to do when iv scan fails

**Comment by RadziQ** [comment]
Ah right. It was due to FastActivated. I checked that now for one scan and there were notifications with fast on and werent with fast off - only the ones that should be (also every pokemon had IV scanned). 
Used it on newest version 17.1 and before on 17 while making this thread.
Thanks ans cheers.
