### ISSUE TITLE
About overlay removal on Sony

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#197]
Hi, @PokeAlert I have Sony Xperia Z1 Compact and the overlay is working fine. It is not crashing just sometimes it closes due to out of memory issue, but this only happens if I minimize the overlay to the bubble, so there is no reason to remove the overlay for Sony devices. You could simply do that Sony devices couldn't send crash reports or something like that but please give us the overlay back because now we will have to stick to 2.3.16 version...

**Comment by RadziQ** [comment]
On my Samsung S4 with battery saving option on (not using 100% phone power), PokeAlert overlay disappears after some time when I play PoGo. Like you said, probably closes due to memory issue.
