### ISSUE TITLE
Gym scan

### ISSUE THREAD

**Issue by RadziQ** [PokeAlert/PokeAlert#198]
Hello again.
So I just encountered this issue: scanned a gym (yellow), then it changed to grey -> red, but when I click on it, it changes back to yellow and shows pokemon that were there before changing team. Goes back to red colour when clicked somewhere else. Had to switch off "Show gyms" option, turn it on and it shows properly now after scan.
Version 17.1.

**Comment by PokeAlert** [comment]
Yea I noticed it as well when testing the other day I'm still trying to figure out why it is doing this.

**Comment by PokeAlert** [comment]
Fixed in 2.3.17-2
