### ISSUE TITLE
Niantic turned captcha ON. Is it over?

### ISSUE THREAD

**Issue by fooentes** [PokeAlert/PokeAlert#204]

**Comment by AbcentMineDead** [comment]
Use a maximum of 20 accounts. Check Dev's Twitter for more details.

**Comment by fooentes** [comment]
thx @AbcentMineDead what's his twitter account?

**Comment by fooentes** [comment]
I'm only  using 12 accounts. Seems like half of them are always returning empty results. Must be stuck behind captcha

**Comment by PokeAlert** [comment]
@fooentes @AbcentMineDead 

As we speak, im intercepting the captch and will return to the user
http://imgur.com/a/2jfda

**Comment by AbcentMineDead** [comment]
Awesome work!!

**Comment by fooentes** [comment]
@PokeAlert great! what's your email?

**Comment by PokeAlert** [comment]
pokealertapp.help@gmail.com

**Comment by PokeAlert** [comment]
GUys @fooentes forwarded me one of his account that was INDEED being ask a captcha!

I'm cleaning up the code and will release a version soon

**Comment by PokeAlert** [comment]
https://twitter.com/ThePokeAlertApp/status/783820519615463425

**Comment by Eric678** [comment]
I am sure they are using the accounts still on 0.35 to get a good AI fingerprint - can turn them off any time. Perhaps they just want to cause those users with 10s - 100s of scan accounts some grief and rein things in gradually.  Will cause a drop off in their user stats which are the universal marketing measure for success in this connected world.

**Comment by AbcentMineDead** [comment]
@Eric678 Very good point. My accounts are dropping like flies. =(

Even with only using 1, 5, 10 or 20 accounts. Gym scans on or off doesn't seem to help or hurt. IV scans on or off doesn't seem to help or hurt.

Just getting smacked left and right even when running 1 account, no gyms, no IVs.

**Comment by PokeAlert** [comment]
@fooentes @AbcentMineDead @Eric678 @juanjo4x4 @MinionAttack 
Yes of course don't forget that we all still are on 0.35 and if they wanted (still dont get why they are doing this??) can ban EVERY SINGLE account in 1 single line

**Comment by Eric678** [comment]
Lots of tries - eventually get the scan to run w/o need captcha popup but still no mon displayed? Account status still says needs captcha - just 1 account.

**Comment by PokeAlert** [comment]
@Eric678 the beta doesn't automatically put backt the account to active. Im gonna release versio  now that will but it is very hard for me because I dont ONE single account returning captcha so i cannot test the code I wrote

**Comment by AbcentMineDead** [comment]
Messaging pokealertapp.help@gmail.com on Google hangouts. Chat there??
