### ISSUE TITLE
Background service

### ISSUE THREAD

**Issue by PeshBG** [PokeAlert/PokeAlert#207]
nothing seems to happen when i turn i on on the new version :(

**Comment by PeshBG** [comment]
[logcat_1475748702242 - copy.txt](https://github.com/PokeAlert/PokeAlert/files/513425/logcat_1475748702242.-.copy.txt)

**Comment by PokeAlert** [comment]
Try restarting the app, nothing wrong in the logs, accounts are all fine.

**Comment by PeshBG** [comment]
found the issue... it is due to nox and the company proxy. Apologies for opening this.
