### ISSUE TITLE
Captcha solver seems not work correct

### ISSUE THREAD

**Issue by MinionAttack** [PokeAlert/PokeAlert#208]
Hi, I've updated the app and while doing a scanner without "Fast scan" and show gims and pokestops OFF I get that 1of my accounts need solve captcha. I go to the menu and press solve. After solve the captcha the "panel" dissapears and I see the Magnemite with the box to probe that you are not a robot.

If the panel disapears I think that the captcha it's solved, or not? On the accounts menu, the account still is being marked as "Requires captcha" and on the scans also show the message to resolve the captcha.

Number of accounts: 19
S.O: Android 6.0.1
Device: Xperia Z3

Thanks for your job!

**Comment by WingChroniam** [comment]
Same issue here

**Comment by PokeAlert** [comment]
@MinionAttack @MinionAttack It will be marked as captcha required until you sucessfully make a scan with it

**Comment by MinionAttack** [comment]
So, I have to solve the captcha all the times until I get a sucessfull scan?

**Comment by Aerow247** [comment]
Same problem here. I Capcha'd a lot and it scanned, but now an hour later only my last 2 (made today) email accounts are working.

**Comment by MinionAttack** [comment]
I've updated and showed the same issue. So I went to PTC web and logic to check if the account was banned. After checked that was still alive I removed the account and added it again. I did a scan I get the error of the captcha so I resolved the captcha and NOW it appears green and not ask again for the captcha. (By the moment).

**Comment by Aerow247** [comment]
I couldn't get my old gmail accounts back to work. I made 18 new PTC accounts with pikapy. Back on the scanning now.

**Comment by PokeAlert** [comment]
Guys try 2.3.18-2

**Comment by MinionAttack** [comment]
For me works, so I close this issue!
