### ISSUE TITLE
A few Questions to the DEV+a few tips for the other(if needed)

### ISSUE THREAD

**Issue by PeshBG** [PokeAlert/PokeAlert#209]
First questions is : how many accounts do you recommend for 1600m? - if I put 100 will that make the scan faster and will that assure less get reCapcha?
Second question: What type of data is send with the request? Does this include phoneID like IMEI or any other information that might flag my main PG account and get it banned? 

Apologies if any of those have been answered.

For the people that are going to use this: I suggest using this : https://github.com/skvvv/pikapy works fine and it takes no more than 10 minutes to create and activate 20 accounts. (use the gmail+ feature)

**Comment by PokeAlert** [comment]
Checkout README
