### ISSUE TITLE
recaptcha notification?

### ISSUE THREAD

**Issue by hurtfrog** [PokeAlert/PokeAlert#210]
Can you add a recaptcha notification? When using background service I don't see the message on screen. Thanks!

**Comment by PokeAlert** [comment]
True, the version I released was a quick fix. Will take to care noww to blend this captcha in the app  better

**Comment by Eric678** [comment]
Cycle in a free account when one gets zapped.  Don't delete a background scan area when all accounts are removed by captchas. Notify if run out of free accounts.

**Comment by PokeAlert** [comment]
all fixed
