### ISSUE TITLE
Captcha: Solved on all accts, see pokemon for a second, swap filter and come back, and then all need captcha again.

### ISSUE THREAD

**Issue by doublefelix921** [PokeAlert/PokeAlert#211]
In addition, when I try to captcha again, I get

Webpage not available
The webpage at
https://pgorelease.nianticlabs.com/plfe/153/captcha/(lots of capital letters and numbers)
might be temporarily down or moved.

for all accounts.

**Comment by klifa90** [comment]
i am having the same problem. When trying to solve more than 1 captcha, i get the message "you need to scan BEFORE solving the captcha" (which i actually have already just done). And when i solve it, it is marked as solved but when re-scaning it goes to needs captcha again

**Comment by PokeAlert** [comment]
Looking into this.  Mean time stop the app.  And reopen

**Comment by klifa90** [comment]
so the steps are:
1) Start scan, 10 accounts need recaptcha
2) do captcha on the first account that needs to recaptcha
3) Start scan again, 9 accounts need recaptcha
4) do captcha on the first account
5)etc

???

I have tried saving all acounts, removing them and adding them all again and it does not fix the problem, i have 15 accounts

**Comment by klifa90** [comment]
Ok so the thing is that captcha solving is not working.

If you need an account to try with, try with this one

ptc
123sad123
aceptar

**Comment by Aerow247** [comment]
I think I have a similar issue. I tried to fix my PTC accounts as less were scanning. I have scanned all night, starting with 20 accounts. In the morgning only 3 remained. The rest all needed captcha.

**Comment by PokeAlert** [comment]
Captcha were broken in the first versions, fix in the latest
