### ISSUE TITLE
Soft ban happening -- FAST

### ISSUE THREAD

**Issue by jagauthier** [PokeAlert/PokeAlert#212]
I noticed my IP is getting soft banned.. fast.  today I turned on pokealert, and within 5 minutes I was unable to see pokemon or spin pokestops.

I disconnected and got a new provider IP... But it was very quick.
I do use many accounts, so maybe lowering that would help?

**Comment by PokeAlert** [comment]
Captcha

**Comment by jagauthier** [comment]
Well, only one account will come up with the captcha message, and then I will go fulfill it's requirements.. or maybe not in time! I'll do more investigation.
