### ISSUE TITLE
New setting: Add 15 seconds for background scan interval?

### ISSUE THREAD

**Issue by Larry1977** [PokeAlert/PokeAlert#214]
While scanning I think 10 seconds is too fast or brief for allowing Pokemon to appear or spawn but 20 seconds seems too long while scanning a search radius of 430m. While scanning a 430m radius many times it's locating Pokemon with too short of time remaining (1 or 2 minutes). Maybe the 5 seconds saved per scan will cover 430m faster?

**Comment by PokeAlert** [comment]
no dif
