### ISSUE TITLE
abnormal behaviour at captcha window

### ISSUE THREAD

**Issue by rhyd3n** [PokeAlert/PokeAlert#217]
Sometimes when I press resolve. The window open but nothing loaded. Press back and account status become alive. Sometimes load but hang when I tick the box to trigger captcha image

**Comment by rhyd3n** [comment]
Update: Unable to reproduce issue upon restart..

**Comment by aaShadow5** [comment]
Same problem. Previous version captcha solver worked fine. Now the new view take a very long time to load or just doesn't show up. If you exit the solver the account is in green even though it's still behind captcha.

**Comment by PokeAlert** [comment]
Captcha window is fixed in the latest version (smaller nicer window)
