### ISSUE TITLE
Solving captcha basically restarts app

### ISSUE THREAD

**Issue by nikola987** [PokeAlert/PokeAlert#218]
This happens with the latest update, and it sucks so hard because app doesn't save my multi area scans, so I need to set them up every time from the beginning :(
Is there a way to save custom scan points?

EDiT: also there is no apk for 2.3.18-5? :(
Plz let us download previous version, this one is not that good. Now caotchas don't even load half of the time.

**Comment by PokeAlert** [comment]
Close app on captcha resolve is fixed, MultiAccount advanced management will come soon
