### ISSUE TITLE
Captcha: Accounts are a ticking time bomb...

### ISSUE THREAD

**Issue by Aerow247** [PokeAlert/PokeAlert#220]
Hi,

Really enjoying the app, just my captcha keeps messing up. The issue is the following:

First thing: When an account dies, after doing captcha once, it will scan and crash again immediately. If I captcha it for the second time, it will be working again.

Second: When I start scanning, it will do 20 accounts. However, they will die one by one pretty fast. I started scanning at 11 pm with 20 accounts and when I woke up at 6am, only 3 accounts were remaining. I had to captcha all the other ones (twice).

I can give you some of these accounts if you want, just send me a PM or anything.

Cheers and keep up the work!

**Comment by MemoriesofNemo** [comment]
Wait, can people actually share accounts this way? I thought one account was only good for one active scanner

**Comment by Aerow247** [comment]
That is true my friend. But I can give him one of my accounts so he can check why this happens. This because the same issue doesn't happen on his own phone.

**Comment by Larry1977** [comment]
Why do people need 20 accounts in the first place? This is insane.

**Comment by PenguinsFlyGood** [comment]
I have 600 accs lol

**Comment by Aerow247** [comment]
Another test update. Last night I scanner from 11pm to 6am again with my 20 accs. 2 accounts were still scanning in the morning.

**Comment by PokeAlert** [comment]
yep, nothing much we can do against captcha. PokeAlert was like always the first app to help user resolve them. If they get triggered far to often, new accounts are the way to go
