### ISSUE TITLE
Softban?

### ISSUE THREAD

**Issue by MemoriesofNemo** [PokeAlert/PokeAlert#221]
It all works great for a while, whilst solving the captchas periodically, but after 1-1,5 hours, all workers show no results at all. Is this because they got softbanned, and is there a workaround for it?

**Comment by hey-tommy** [comment]
I believe the no results we're all currently experiencing (as of the past 30 mins or so) is due to a server-side update by Niantic. This could be the damn 0.35 API shutdown we've all been fearing...

**Comment by seonghoon85** [comment]
Goodness gracious... Just when I finished going through captcha on my accounts.... this happens...

**Comment by RadziQ** [comment]
Somebody posted that Niantic updated safety again.

**Comment by MemoriesofNemo** [comment]
This is getting beyond frustrating. Lets see how long it takes before someone manages to break through though.. Might aswell try to stay positive

**Comment by divnotded** [comment]
Niantic has just disabled the .35 API.

Of course, this means anything using pgoapi will not be working at this time. There's very little the PGM devs can do.

Let's wish the RE devs luck in cracking this.

Please don't ask for any ETA. We don't know, nor does anyone else.(edited)

**Comment by Larry1977** [comment]
The dev's warned us about this last week. Not surprised at all
