### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by jumblox** [PokeAlert/PokeAlert#222]
Scans show no pokemon for the past 12 hours or so. Is this the end? Or is there something I can do to fix the problem in my end?

**Comment by pokris109** [comment]
For me too no results....

**Comment by Elo1338** [comment]
Guys, I am really wondering how you couldve missed, what's all over every Pokemon Twitter account, subreddit whatsoever. The API 0.35 is no more usable because of a forced update. So no scanner is working anymore. We have to wait until the scanner developers crack the new 0.39 API.

**Comment by walaoaaa1234** [comment]
Yes, 0.35 API is disabled.
[Reddit](https://www.reddit.com/r/pokemongodev/comments/56djcm/35_api_has_been_disabled_all_3rd_party_access_is/)

**Comment by PokeAlert** [comment]
thanks
