### ISSUE TITLE
Question about spawnpoint times

### ISSUE THREAD

**Issue by coldfire003** [PokeAlert/PokeAlert#223]
Can you say how the time formatted from spawn point data? From my old spawn point data for instance: 

time1: 1475289535524
time2: 1475289999604

I can tell the last 4 digits are for minutes and seconds as a pokemon spawns next to my house at every 55th minute (for time1), but time2 says the minute to be 96. Also what are the first 9 numbers suppose to represent?

**Comment by PokeAlert** [comment]
these number are the miliseconds since the start of time if you want to know in human reable time put that number here
https://currentmillis.com/
