### ISSUE TITLE
Not scanning

### ISSUE THREAD

**Issue by sophistidecay** [PokeAlert/PokeAlert#225]
Built new filter loaded old accounts. Not scanning all accounts show alive.

**Comment by lotsobear** [comment]
same...i manual scanned San Fransisco and it worked, but it did not work for my suburban city.

**Comment by Num1Phat** [comment]
bummer.  was super excited when I got the Happy Halloween alert.  But same as above.  Scans not working.  :(

**Comment by leluc42** [comment]
scan not working

**Comment by Aerow247** [comment]
I have the same.. no circles, no pokemons

**Comment by Aerow247** [comment]
I see no circles, but it is scanning sometimes. But sometimes it doesn't seem to scan. It seems to be working different than before...

**Comment by arhi3a** [comment]
From what i saw it takes pokemon data from FPM cache so all pokemon seen in fastpokemap will be also shown in pokealert app. But scanning with accounts is still not working I think.

**Comment by Larry1977** [comment]
Same here. New build looks nice but useless since it finds nothing. The reverse API was leaked back to Niantic so I'm sure they blocked our scans

**Comment by Larry1977** [comment]
funny how FPM is down at the same time

**Comment by RadziQ** [comment]
People said PokeAlert took from FPM so that's why.
