### ISSUE TITLE
Pokemon not showing on map

### ISSUE THREAD

**Issue by evilmoses** [PokeAlert/PokeAlert#226]
I am getting notifications for pokemon, but nothing is showing on the map, both with low res and high res icons.

**Comment by Num1Phat** [comment]
I have Note 4 with Marshmellow.  I am getting neither notification nor pokemon displayed on the map.  I have tried my normal filter, and with setting the filter to show and notify for everything.  I have tried scanning in known high density pokemon areas in my area.

**Comment by PokeAlert** [comment]
server were down
