### ISSUE TITLE
Switch / Restart Problem

### ISSUE THREAD

**Issue by Jamducat** [PokeAlert/PokeAlert#227]
If i switch to another app, then switch back to pokealert by clicking on the link on home it seems to do some complete relaunch (map is zooming in) an then the complete graphic interface is fucked up. the scan-circles dont disappear and it doesnt draw any pokemons. scan seems to continue (alerts work). Also no erase is possible then.
But everything works on first start. So if this happens i need to kill it with task manager and restart it. Then everything is fine again.
If i switch apps by choosing "recent apps" then it works. Just the click on the link on home seems to kill something in the app.
Already tried to uninstall/reinstall and recreate the link. Did not help ...
Samsung Galaxy S6/Android 6.0.1

**Comment by Jamducat** [comment]
seems to work now after i upgraded to 4.0.1-1

**Comment by Jamducat** [comment]
it happend again after clicking on a notification. everything was fine yesterday. so i don't know whats causing it ...
here you can see how this looks like after a while:
no pokemons, lots of circles 
![screenshot_20161105-093357](https://cloud.githubusercontent.com/assets/23262959/20028805/97634152-a33b-11e6-9500-750df002ebbb.png)

**Comment by PokeAlert** [comment]
Fix in 4.0.5
