### ISSUE TITLE
Background Scanner Services doesn't work, but Counter-Clockwise Arrow Refresh works

### ISSUE THREAD

**Issue by CreativiTimothy** [PokeAlert/PokeAlert#231]
Hi. I'm running 10 accounts that all say they are alive. For some reason, no pokemon pop up if I turn on the background scanner service which is that blue radar icon. However, if I turn on the counter-clockwise arrow refresh thing below that, it shows up Pokemon just fine. I checked my filters to make sure they weren't causing the problem. My background service is set to scan every 20 seconds, but I've waited 10 min and nothing popped up. The counter-clockwise arrow thingy causes Pokemon to pop up almost instantly though.

I have a rooted Moto 2G if that makes any difference.

**Comment by WalterMagnum** [comment]
Is the app receiving your correct location?  The background service is centered at your GPS location no matter where your screen is focused.

**Comment by CreativiTimothy** [comment]
@WalterMagnum Ah, turns out my GPS was not centered correctly. Solved the problem by resetting my GPS settings. Thank you!
