### ISSUE TITLE
Download link looks sketchy as hell

### ISSUE THREAD

**Issue by echo465** [PokeAlert/PokeAlert#239]
What is this crap?  It looks like some warez site from 1997.

**Comment by Eric678** [comment]
+1 why is it not on github directly?
As for forcing the update supposedly switching off the servers - what if a user is in the field and does not want to bill it to mobile data?

**Comment by AqibShirwani** [comment]
It is available on github now @Eric678. Plus the other websites it was on were safe.

**Comment by PokeAlert** [comment]
The other side was
