### ISSUE TITLE
background notification list is unmodifiable

### ISSUE THREAD

**Issue by Stereolab42** [PokeAlert/PokeAlert#24]
2.2.9:

1. Turn on background service.
2. Go to "notification filter".
3. Notice all 151 mons are selected. Deselect some or all. Click "save".
4. Notifications are still being gotten for the mons you deselected. Return to "notification filter". Notice that yet again, all 151 mons are selected.

This renders the app completely useless. I tried variations such as changing the filter only when the service is off and so on, but it always reverts to 151 selected when turned on.

**Comment by demolina** [comment]
Strange. This works properly for me. I even added Rattata to my Notify list just now and it worked as expected.
Samsung Galaxy S6, Android 6.0.1. 

Have you tried wiping the app settings and starting over?

**Comment by Stereolab42** [comment]
Yup, no luck. Samsung Note 4, Android 5.1.1.

**Comment by Stereolab42** [comment]
Issue still not addressed, background scanning still useless.
