### ISSUE TITLE
Expire time is always over 1 minute

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#245]
Hello, I am super excited that Pokealert is working again. However, I have noticed that no matter which pokemon I tap it doesn't show the exact expiration time, but shows "over 1 minute instead". 
![screenshot_2016-11-08-09-37-38](https://cloud.githubusercontent.com/assets/12085708/20090759/c5933b64-a597-11e6-8601-792cbd7f216e.png)
Only the notifications are showing time correctly.

**Comment by RovingSpirit** [comment]
Niantec broke information from the server. It's why fastpokemap isn't working and it means they can't get the exact time left from them

**Comment by happypokemonhunter** [comment]
I get "over 1 minute" as well. But if that's the case then why does the notification show 14 mins 59 secs? So is it really not that long and it could be anything?
