### ISSUE TITLE
Android 7.1 cannot use the locked area

### ISSUE THREAD

**Issue by xordis** [PokeAlert/PokeAlert#250]
I have 4.0.3 installed on 7.0 and it appears to work. (Nexus 5x).
I just installed 4.0.3 on 7.1 on a Google Pixel XL and it can't seem to use the lock feature.

Will confirm the version on the Nexus when I get home but I am pretty sure it's 7.0

Symptom 
- click on the lock
- select accounts
- back to map

from here you can start the locked scan.

As soon as you try to add a second area it deletes the first one.

**Comment by hardknoxni69a** [comment]
do you have multi scan area in setting enabled

**Comment by xordis** [comment]
arr bugger. 
I didn't even remember that setting.
All sorted. sorry for the ticket.
