### ISSUE TITLE
[BUG] Setting more than 1 Pokemon "Show / Notify when IV fails" fails

### ISSUE THREAD

**Issue by CreativiTimothy** [PokeAlert/PokeAlert#251]
Hi. When I select multiple Pokemon in the filters and deselect "Show when IV fails" and "Notify when IV fails", the Pokemon I selected still have those checkboxes selected. It's an annoying bug because it takes a while to press the Pokemon but then in the end you didn't change anything. However, changing the settings for "x when IV fails" works completely fine if you do one Pokemon at a time.

Steps to reproduce.
1) Select more than one Pokemon
2) Click on the options gear icon
3) Deselect "Show when IV fails" and "Notify when IV fails"

4) After saving the settings, go back and check one of the Pokemon you changed the settings before. You will see that "Show when IV fails" and "Notify when IV fails" remain selected even though you tried to deselect them

**Comment by happypokemonhunter** [comment]
Yes, I have the exact same issue. I thought it was just me! What I did was manually go through each Pokemon and unticked the two boxes. Tedious, but now my phone doesn't notify me every few minutes.
