### ISSUE TITLE
[Transaltion] problem in use_multi_area_scan_summary

### ISSUE THREAD

**Issue by terrylinooo** [PokeAlert/PokeAlert#254]
<string name="use_multi_area_scan_summary">Select multiple area that will be scanned by different accounts (this is an advance user feature and might get your accounts by faster if incorrectly)</string>

I'm translating the the file to Chinese. This line seems to be incorrect.
I don't understand , "get your accounts for what? by faster if "incorrently". Is it corrently or incorrently?

**Comment by PokeAlert** [comment]
Yes it is meant to say:
Select multiple area that will be scanned by different accounts (this is an advance feature and might get your accounts banned faster if used incorrectly)

**Comment by terrylinooo** [comment]
Thanks for replying, I got it, fixed the translation of my pull request
