### ISSUE TITLE
IV Display is messed up on my phone

### ISSUE THREAD

**Issue by zimmey** [PokeAlert/PokeAlert#256]
I have a note 3, the app is running amazingly. The only issue is the IV display is not aligned properly, and the # for Attack is shown over top of the number for Stamina. I've attached a photo to show.

This is consistent.

![iv-status](https://cloud.githubusercontent.com/assets/1965673/20193368/80a287f6-a742-11e6-80c3-eb390a4d69de.png)

**Comment by PokeAlert** [comment]
will be fixed in 4.0.4
