### ISSUE TITLE
Incorrect moveset for snorlax

### ISSUE THREAD

**Issue by zimmey** [PokeAlert/PokeAlert#258]
I've recently captured a Snorlax, with moveset listed in pokealert as "rock throw fast" and earthquake.

In reality, it was "Lick" & earthquake.

**Comment by PokeAlert** [comment]
I only show what the server returned me. This is strange

**Comment by zimmey** [comment]
I wasn't sure if an integer move # was sent from server, and it was just an incorrect lookup in an array or something. If it is passed as a string, they likely changed the move type. I don't think I've seen a snorlax with rock throw.. maybe they changed their mind and swapped it with Lick. Who knows.. niantic.
