### ISSUE TITLE
Pokemon don't show up if you click on notification while on account screen; restart fixes

### ISSUE THREAD

**Issue by CreativiTimothy** [PokeAlert/PokeAlert#261]
Hi. 

If you are on the account or filter screen and click on a notification like "Lapras found!", no Pokemon will show up on your map when the app loads. This applies to all versions include beta. The way to fix this is to restart your app. The way to avoid this problem is exit the account / filter screen before clicking your Android notification

**Comment by PokeAlert** [comment]
I think I fixed this in 4.0.4-6
