### ISSUE TITLE
App notifies twice or more for 30min+ spawns

### ISSUE THREAD

**Issue by CreativiTimothy** [PokeAlert/PokeAlert#262]
Minor bug. If a spawn is 30 min or more, it will notify you more than once which can confuse you.

**Comment by happypokemonhunter** [comment]
Well ts technically not a bug. The Pokemon is still spawing there and exists, it's just that you cant catch/encounter it again if you've already caught it or its ran away.

**Comment by CreativiTimothy** [comment]
It technically is a bug. Per Pokemon ID should only notify once, not twice for 30 min spawns or thrice for 45 min spawns. I might reopen this issue again if this becomes too annoying.
