### ISSUE TITLE
timer

### ISSUE THREAD

**Issue by NickeyEx83** [PokeAlert/PokeAlert#266]
Help me. My scan all the pokemon and all is expired over 1 minute, how can I settle this problem?

**Comment by tassietigermaniac** [comment]
Same here, it only shows a time when it's under 1 minute left. Everything else just doe shows expiring after more than 1 minute

**Comment by rezecib** [comment]
It's difficult to solve this. I believe that at the moment Niantic's servers only send whether it's >90s or the time remaining if it's less. It might be possible to have it remember when it last scanned each area and guess the range of spawn time based on some assumptions, but it would be tricky to do.

**Comment by tassietigermaniac** [comment]
Makes sense. Nothing that can be done about that for now
