### ISSUE TITLE
Scans showing no pokemon

### ISSUE THREAD

**Issue by rezecib** [PokeAlert/PokeAlert#267]
I have 10 accounts that I almost exclusively just run scanning the 550m area around where I live. After running for a couple of hours, they stop finding any pokemon-- the scan area will just be blank after the circles have swept over. This happens even with the latest release, 4.0.4

I'm guessing this is a soft ban, but I'm not sure if there are any other diagnostics or techniques I could try to avoid this happening. Would it be possible to maybe adjust the timer on how frequently an account shifts areas during a scan, or stagger it in any way? I'd imagine Niantic could see something suspicious from 10 accounts always scanning at almost exactly the same time.

The only solution I've found so far is to turn off scanning for several hours before starting it again.

**Comment by tassietigermaniac** [comment]
It's probably an IP ban. Try accessing it off a different WAN IP (like swapping from wifi to mobile data) and scanning again to test. I don't know what their conditions are but I've heard Niantic are tightening up on the amount of requests that can come from an IP.

One person on Reddit mentioned after testing they completely avoided the softban on 17 accounts. I've never tested it myself though.

https://reddit.com/r/pokemongodev/comments/5catgo/pokealert_getting_me_softbanned_on_the_actual/
