### ISSUE TITLE
[Bug] Notifications no longer appear for a filter if you change filters by activating

### ISSUE THREAD

**Issue by CreativiTimothy** [PokeAlert/PokeAlert#270]
At first, when you create a filter and don't activate another one, it will work just perfectly fine and notify you like normal. However, if change filters by pressing "activate", you will no longer get notifications. Pokemon will still show up according to the filter, but there are no notifications so you must look manually

**Comment by CreativiTimothy** [comment]
Just tested. This only applies to background service scan. The manual refresh scan notifies fine. It used to be the other way around haha. Hopefully both of them notify and get fixed soon

**Comment by CreativiTimothy** [comment]
This also applies if you modify the filter in any way

**Comment by PokeAlert** [comment]
I have tried an filter are applied correctly.

ca you please post a step by step?

**Comment by CreativiTimothy** [comment]
@PokeAlert I reinstalled the app and it apepars to have fixed the problem. If I come across the problem gain, I'll try to tell you step-by-step  to reproduce
