### ISSUE TITLE
[Bug] Can't unlock search area

### ISSUE THREAD

**Issue by coryallegory** [PokeAlert/PokeAlert#271]
After the latest update, 4.04, I can't unlock or move the search area. I would expect once a lock is set and the icon is blue, that I could tap it once to drop the lock, however it prompts as if you are setting the lock every time (this behavior was present before the update)

**Comment by coryallegory** [comment]
Closing this bug, I've figured out that the intention is to allow multiple fixed search sites. Tapping a fixed site is the correct way to remove any committed search accounts.

**Comment by macinmn** [comment]
I was having a problem figuring it out too, so thank you
