### ISSUE TITLE
Account Banning

### ISSUE THREAD

**Issue by Num1Phat** [PokeAlert/PokeAlert#272]
I don't know if it's this new version or not, but I had 13 gmail accounts that I've never had a problem with, suddenly get banned today, all at the same time.  Just a heads up.

**Comment by darkseid117** [comment]
I've experienced the same thing, however I had one PTC account that I used in conjunction with 3 gmail accounts that was also banned. After checking the email the PTC account is associated with, there was email stating the account had been banned. I'm wondering if the accounts may not actually be banned, but this is purely speculation.

**Comment by Num1Phat** [comment]
Well, I went to login to the 13 various Gmail accounts to see if I had received any e-mails.  It appears that Google may have disabled all of the accounts.  The accounts were simply ones that I created for the sole use of Poke Alert.  Never signed into them or used them for anything.  Today would have been the first time I tried signing into them since creation.

Google is requesting a number for some automated SMS stuff for verification of account ownership, but I'm not going down that road.  I think I may have just lost 13 accounts, but oh well.  A bummer since it took me a little bit of time to create them, on the road a bit and would create a couple in every city I went to.  And will now take awhile to build them back up.

Lesson Learned, login every now and then into any fabricated Gmail accounts to keep them intact.

Maybe, unless there is another issue.  :(

**Comment by xtrmdev** [comment]
All my accounts got banned today. I was able to login to all of them on google.
So i guess they managed to detect it somehow..

**Comment by juggalokyle** [comment]
I had all 4 of my accounts banned today and I've never had an account banned.

**Comment by Num1Phat** [comment]
Well isn't this just the shts...  I wonder if it was a result of the last PokeAlert update....  :(

**Comment by dpatton421** [comment]
I got banned today too. Updated poke alert yesterday got banned today only had 3 accounts attached. Wtf I updated because it said to avoid ban update now BS!

**Comment by Num1Phat** [comment]
@dpatton421, Yeah, thats EXACTLY what I was thinking.  Now I want to kick myself in the ass because I usually wait a few days before I update to see if there's any issues.  But they've been so good so far, that I went ahead and updated...  Now I'm out 13 accounts.  :(

**Comment by Num1Phat** [comment]
Also hesitant to put the effort in to create more accounts if this is an APK problem.  If so, any new ones will be banned fairly quickly as well.   Stuck.

**Comment by beefsticks** [comment]
Was having a great time til forced to update to 4.0.4, now I'm banned. Broke something that didn't need fixing. Still being forced trying to back to 4.0.3 and can't even use it.

**Comment by beefsticks** [comment]
Just checked the Twitter, has nothing to do with the update, guys. Every 3 weeks accts with no catches are banned.

**Comment by oTeMpLo** [comment]
My 9 Days old account got banned to !!! :(

**Comment by dpatton421** [comment]
I didn't get an email saying my account was banned just get the notice when trying to log in it says it's suspended...... what does that mean?

**Comment by PokeAlert** [comment]
Create new accounts. Life goes on.
