### ISSUE TITLE
Enhancement: show estimated pokemon level in UI

### ISSUE THREAD

**Issue by rafalh** [PokeAlert/PokeAlert#273]
Im trying to find pokemons for Bubblestrat strategy (level 1-2) but its not easy when using 26. level account. Could you add to UI information about estimated pokemon level? I read somewhere that if multiple trainers with the same level encounter a pokemon, its CP is the same for them. Therefore pokemon CP/level is global parameter and could be estimated by PokeAlert. If there is no information about pokemon level in proto (if I read correctly there is only CP) it would require to train PokeAlert accounts to have better accuracy (if I understand correctly 1. level worker can only encounter pokemons with 2 different CPs). Showing estimated level could be in advanced settings to not confuse people who dont know how it works.
Encoutered pokemon level is relative to trainer level so app could show level in percentage.

**Comment by CreativiTimothy** [comment]
That would be nice yeah. To make it useful, you'd have to bot all your scanner accounts to your desired level though. I'm lvl 35 although lvl 30+ is all the same. So I would need my scanner accounts to be lvl 30, and if PokeAlert decides to implement it.

**Comment by rafalh** [comment]
That's why I said "estimated". If workers have smaller level it should be possible to predict level with some precision based on workers level. Level 5 worker could give me 6 possible outputs and its better than nothing. Training workers to level 30 would be too time-consuming for me.

**Comment by terrylinooo** [comment]
It is fun, bot your scanning bots to level 30 and then they get banned, lol

**Comment by PokeAlert** [comment]
Boting is a direct ban if done incrrectly

**Comment by rafalh** [comment]
Hey! I didnt say PokeAlert should be botting. I only asks for information about Pokemon level/CP in PokeAlert UI. Training workers is another problem out of this issue.
