### ISSUE TITLE
Icons Size x2 

### ISSUE THREAD

**Issue by ATOG2074** [PokeAlert/PokeAlert#274]
First of all love the app 

i have some dificulties with the icons 
normal are to small and HD are way to bigg 

maby a option for 2x size of the small icons ;-)

**Comment by PokeAlert** [comment]
Yea I now I need to find how to resize them properly according to each screen. There is alreayd an open ticket for this

**Comment by terrylinooo** [comment]
Maybe you don't need to know how to resize them, just put another "bigger" version icon set in the setting options. It saves your time.

Do you need what size ? I can make it for you

**Comment by ATOG2074** [comment]
yes "just" resize the icons and give it a new set name
