### ISSUE TITLE
No pokemon icons

### ISSUE THREAD

**Issue by jdinh1** [PokeAlert/PokeAlert#275]
Just downloaded this app for the first time today. Scanning is fine but I don't see any pokemon icons on the map at all even after notification shows that there are pokemons near me. Switching between defaul and HD icons does not help either.

I'm using SS Galaxy S6, on 6.0.1.

**Comment by PokeAlert** [comment]
There is a big that often happen after an update ( go figure) when the scan works but nothing is displayed on the map. When you see this please just kill the app and restart
