### ISSUE TITLE
scan does not remember accounts chosen

### ISSUE THREAD

**Issue by Stereolab42** [PokeAlert/PokeAlert#277]
Ever since the update a few days ago, EVERY time I select "scan", I'm asked to choose accounts. And none are selected by default, so I have to click a checkbox. That's two extra annoying mouse clicks and a checkbox hunt for every scan. For someone who likes to scan around multiple times in a row to checkout gyms, this makes the app unusable.

**Comment by PokeAlert** [comment]
done in 4.0.4-6
