### ISSUE TITLE
(<Feature Request>) Amazing IV Bypass Filter Idea

### ISSUE THREAD

**Issue by hardknoxni69a** [PokeAlert/PokeAlert#281]
I Believe The Community Would Absolutely LOVE The Option To Bypass Filters For A Set IV. So There Is A Lot of Pokemon That I Don't Care To Have Displayed On My Map Because There Everywhere Pidgey, Rattata, Nidoran, AND Basically All The Common Pokemon. I Have It Set So They Are NOT Displayed But It Would Be Amazing if There Was A "IV Filter Bypass + Notification" Setting So I Could Set It To Say 90IV And Any Pokemon Over 90 IV Would Bypass Filter And Display On Screen And Make A Notification. This Setting Would Basically Make Any Pokemon Over 90 OR Whatever IV Value The User Specifies Automatically Display On Map With IV And Notify As If All Filter Settings Were Checked Instead Of Unchecked

**Comment by terrylinooo** [comment]
This feature already exists inside the App.. you should take a look by long-click on the pokemon you want to set up.

**Comment by hardknoxni69a** [comment]
The setting your talking about is slightly different that advanced one doesn't even show up unless you have that pokemon enabled. I'm talking about a bypass that will override all settings for a 90iv or 100iv pokemon even if the pokemon is off. I have every pokemon already so all the common pokemon I don't have enabled at all  no checks next to there name but with the new setting if a 90+ iv pokemon was scanned it will bypass basic settings and notify user that there is a better version available.

**Comment by PokeAlert** [comment]
This seems a bit redundant. Whats the point of having this override? if you want to see a pokemon just filter it a set the iv you want no? (aka >90%)

**Comment by terrylinooo** [comment]
You are just lazy.

**Comment by Num1Phat** [comment]
I agree.  Basically lazy.  I currently have a filter in place that will show/notify nothing but 100% IV and a few select 'mon no matter what the IV, i.e. Lapras, Aerodactyl, etc...

**Comment by lmcarreiro** [comment]
If you select all before enter in the advanced settings, then the changes Will apply tô all selected pokemons
