### ISSUE TITLE
Workers getting banned quickly

### ISSUE THREAD

**Issue by cooler67** [PokeAlert/PokeAlert#282]
I'm starting to notice the workers are getting banned very quickly now. They are starting to drop off one by one. Getting annoying having to always make new accounts to replace the banned ones. Is there a easier way to make batch of accounts ?

**Comment by PokeAlert** [comment]
4.0.4-6

**Comment by cooler67** [comment]
I was doing a scan with 5-6 workers at a time with default settings, then went to a single account with a smaller scan area, still getting them banned all the time. Yet when I use PokemonGo-DesktopMap I'm fine.
