### ISSUE TITLE
Account creation problem

### ISSUE THREAD

**Issue by zimmey** [PokeAlert/PokeAlert#288]
The Terms of Service isn't clicked, avatar isn't selected, and starting pokemon hasn't been selected.

These accounts will get banned quickly I think...

The accounts are difficult to log into due to the long random characters... it may be a good idea to use a dictionary and join a couple of words and a random number or something.

**Comment by Num1Phat** [comment]
I'm not sure if I'm doing something incorrect, but, when I try to create 10 accounts, I get stuck in an endless reCAPTCHA loop.  I do the captcha, select continue, then it begins to create another account and goes straight to another captcha.  And it's endless.

**Comment by PokeAlert** [comment]
@Num1Phat Wrong email. try Gmail onces

@zimmey On what are basing this? These information are not filled during account creation time. They are filled when you first scan with that account

**Comment by zimmey** [comment]
Apologies, I guess it was a lack of documentation. I just checked the account after creation to find those. I hadn't done a scan yet because I was concerned about them being instantly banned.
