### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Krannich479** [PokeAlert/PokeAlert#29]
Hi, 
the App crashes constantly after start with this 'PokeAlert - Notification for Pokemon GO closed' ERROR Message since I tried to install the new 2.3.0

Android 6.0.1
Sony Experia Z5 Compact 

(already tried re-install)

**Comment by nesocharis** [comment]
Same problem here. Another device works perfectly.

**Comment by joesomebody666** [comment]
Can you install earlier version of the app and it works? Or are all the versions produce same result now?

**Comment by Krannich479** [comment]
Tried 2.2.9 before and it worked well

**Comment by PokeAlert** [comment]
Hey guys!
Sorry about these crash, I had updated a lib that didn't play well with some Android version...
All fix in version above 2.3.4

**Comment by Krannich479** [comment]
2.3.4 Workshop fine! Thanks

**Comment by PokeAlert** [comment]
Version 2.3.6-1 is out and even more powerful :)
