### ISSUE TITLE
[Suggestion] strings.xml update

### ISSUE THREAD

**Issue by terrylinooo** [PokeAlert/PokeAlert#295]
Please and I will translate it into Chinese for my friends who don't read English.

**Comment by PokeAlert** [comment]
Yep, sorry about that I will bundle up all the new string tomorrow

**Comment by PokeAlert** [comment]
Here we go I have update the latests strings
https://github.com/PokeAlert/PokeAlert

**Comment by terrylinooo** [comment]
Just updated.
