### ISSUE TITLE
Locked Scan

### ISSUE THREAD

**Issue by braddash** [PokeAlert/PokeAlert#301]
I cannot figure out how to unlock a scan area. I tgink I dix it last night.night pressing random buttons but now have tried a dozen times and cant get it to work. I think I did it before by pressing the lock button again and there was an option to delete at the bottom between cancel and save. Now the button is locked blue and when press it again, tried at least 10 times, it only gives me an option to save our cancel.I can still press other buttons but the lock button remains blue so im not sure what's going on.

**Comment by PokeAlert** [comment]
tap on grey area
