### ISSUE TITLE
Any tricks to avoid mass captchas?

### ISSUE THREAD

**Issue by datrinh** [PokeAlert/PokeAlert#307]
Most of my accounts require solving captchas all the time. Are those flagged as bad accounts and should be disposed of? 
Is there any configuration of settings that reduces this problem?

**Comment by rookie2222** [comment]
I've got the same going on, no clue what to do as with 10 accounts its already stopped completely within the hour. currently running at a radius of 1000m

**Comment by niqwilk** [comment]
I think ever since the update where "search algorithm was optimized" this happened. Before this k would get at most 2 captchas on 50 accounts now it's over 10 with EVERY scan. PLEASE go back to old search algorithm

**Comment by jsherin** [comment]
I'm also getting tons of captchas recently. I created all new accounts yesterday but the captchas came back within 5 minutes

**Comment by PokeAlert** [comment]
We didnt crack the new api so there isnt really a trick. unless you scan in small wave of 5 min you will get captcha
