### ISSUE TITLE
Ditto identification

### ISSUE THREAD

**Issue by lmcarreiro** [PokeAlert/PokeAlert#308]
Some people said that when a pokemon is a transformed Ditto, it make a different sound... must be a way to identify these pokemons...

**Comment by vmwinckler** [comment]
agree

**Comment by PokeAlert** [comment]
we cant. it needs to be caught

**Comment by vmwinckler** [comment]
But you dont need caught to identify IV ? If you caught, you identify Ditto. :)

**Comment by AdrienNguyenWorldline** [comment]
Actually, we may be able to find ditto with the encounter data, the Catch Rate returned by the server is way lower then it should be for the same pokemon. By comparing returned CR with average CR for that pokemon at a given level we could know wich ones may be ditto.
