### ISSUE TITLE
Captcha Fragment

### ISSUE THREAD

**Issue by bigmasa** [PokeAlert/PokeAlert#309]
Please set the layout_width of the Captcha Fragment to match_parent. It is unusable with a tablet. 
Thx
Greetings Marc

**Comment by PokeAlert** [comment]
done in 4.0.5. Please let me know if that fixes it for you.

**Comment by bigmasa** [comment]
Hi, 
Now I'm able to select the images. Thx 
It doesn't look greet because the capture dialog is on the right side, but this is only nice to have. 

Great work!

Marc
