### ISSUE TITLE
No pokemon scanned

### ISSUE THREAD

**Issue by grimley87** [PokeAlert/PokeAlert#311]
I have 50ish accounts loaded and I'm being constantly bombarded by the captchas. Once I get them all solved I look at my main screen and no Pokemon show up. I'm guessing it's because of the new update. But at the moment it's completely usless for me. Hopefully it gets fixed soon. Love the work that you have done so far.

**Comment by PokeAlert** [comment]
Sometimes it happend because th server reject the captcha. Try again in 30min or 1h
