### ISSUE TITLE
Don't display pokemon after click notification.

### ISSUE THREAD

**Issue by hoanhdo** [PokeAlert/PokeAlert#314]
step 1:  run background scan.
step 2:  go to account setting, do some thing like long press to account.
step 3:  click to notification to open pokealert.  All pokemon in map missing.

I play pokemon on nexus 4 , android 5.5.1 rom stock.
It make i can't solve capchat while scanning map. :(

**Comment by PokeAlert** [comment]
Finally fix that bug
