### ISSUE TITLE
Captcha Screen

### ISSUE THREAD

**Issue by LegornSunrise** [PokeAlert/PokeAlert#321]
The captcha screen in version PokeAlert_4.0.5-1.apk is too small

**Comment by AqibShirwani** [comment]
Same issue

**Comment by CreativiTimothy** [comment]
For me, it's too big and I can't see part of the picture and the text above. The old way was good for me

**Comment by LegornSunrise** [comment]
The PokeAlert_4.0.5-2_PokeMesh_common_DB.apk solved my problem!
Thanks!
