### ISSUE TITLE
Show Ditto instead of it's transformed form.

### ISSUE THREAD

**Issue by PeggerWed** [PokeAlert/PokeAlert#328]
There's a Chinese website that shows pokémon online on a map and it shows Ditto in it's actual form.

https://pokemon.appx.hk/

Is it possible for PokéAlert to show Ditto also in it's actual form instead of the transformed one?
This should really make it easier to catch just Ditto and not catch all pidgey/ratatta/Magicarp/Zubat shown on map.

**Comment by arhi3a** [comment]
From what i know only way to find dito is catching all the pokemons, and they are probably catching every ratata/pidgey/magikarp to find ditto and put it on map. It increase ammout of captcha + your scanning accounts will be banned much faster.

**Comment by vmwinckler** [comment]
+1

**Comment by AdrienNguyenWorldline** [comment]
Actually, we may be able to find ditto with the encounter data, the Catch Rate returned by the server is way lower then it should be for the same pokemon. By comparing returned CR with average CR for that pokemon at a given level we could know wich ones may be ditto.

**Comment by PokeAlert** [comment]
done in 4.0.5-5

**Comment by vmwinckler** [comment]
Plz. Add "Pokemon Origin" in description... example "Ditto(Pidgey)(71%)"... "Ditto(Rattata)(71%)"... "Ditto(Zubat)(71%)" ... "Ditto(Magikarp)(71%)"
