### ISSUE TITLE
Grouped crowdsourced server

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [PokeAlert/PokeAlert#332]
Would it be possible to add webhooks to send to a common server the pokemon founds and pull what other people have scanned, like Scan Go did ?

For security, adding a private key auth would be nice. That could be done with JsonWebTokens.
I can take care of the server side, but not android devs.

**Comment by PokeAlert** [comment]
This is already being done. we have a common database with Pokemesh

**Comment by gauravyadav26** [comment]
How to use that common database?

**Comment by drallieiv** [comment]
is that database openly readable ? if not ,could it be possible in advanced configuration to set our own target persistance ?
