### ISSUE TITLE
Save data to Firebase

### ISSUE THREAD

**Issue by Darknite24** [PokeAlert/PokeAlert#333]
Is there any possibility you could add a feature to save found pokemon to a Firebase database? It's only about 12 lines of code. Or if you wanted a contributor, if I had access to the source code, I could make it happen pretty quickly.

**Comment by PokeAlert** [comment]
There would be no authentication? or if there is there will be all inside the apk naked. Poeple will be able to use it to upload fake spawn

**Comment by Darknite24** [comment]
I'm thinking a configuration setting so a user can enter their private firebase app key and when set, data would upload to their private firebase backend. Not for general consumption but for personal use of the user who owns the firebase app.
