### ISSUE TITLE
Suggestion: IV Filter

### ISSUE THREAD

**Issue by LegornSunrise** [PokeAlert/PokeAlert#335]
Greetings!
I think it's a nice idea to add and IV filter per pokemon type.
Ex: It will only appear on your map pidgeys of 90%+ 

Congratulations on the amazing project! Keep up with this nice work!

**Comment by piotrrr** [comment]
Go to filters, choose filter, click on desired pokemon, click 'advanced filters', select desired IV.

**Comment by LegornSunrise** [comment]
Thanks piotrrr, didn't see that.
