### ISSUE TITLE
Mute solve captcha notification

### ISSUE THREAD

**Issue by kopnoob** [PokeAlert/PokeAlert#336]
With the recent increase in captcha's it's getting annoying with all the sounds from notifications, resulting in me having to turn off sound entirely if I want to keep Pokemon notifications. It would be great if these notifications could be muted just like you can change sounds for different Pokemon.

An option to turn off captcha notifications entirely would be great as well. With 60 bots running, it's always gonna be a few to solve, so I don't really need a notification, since I'll go and check once in a while anyway, maybe a notification for a certain number of bots down, like 50 % being a critical low.

Thanks for a great app, donating for sure!

**Comment by paulking00** [comment]
+1
It would be great to have an option to turn off notifications for captchas completely

**Comment by PokeAlert** [comment]
ok will be in 4.0.6-3
