### ISSUE TITLE
 I lost my pokémons

### ISSUE THREAD

**Issue by Cosfjinho** [PokeAlert/PokeAlert#338]
I started using the application yesterday, during the last day of the tranksgiving event, but after using the application and stopped playing I noticed that my 8 strongest Pokémon simply DID, why did it happen and why is there no warning about it? Among my lost pokemons are: Charmeleon, Kadabras, Rapidash, Onix, Exeggutores, Rhydon (My strongest, with 98% IV) ...

**Comment by aaltaay** [comment]
I'm going to cry. I lost at least 20rariest and strongest Pokemon (2000cp and above) even the ones I kept as 'favorite'. I was about to evolve all of those piggys , I was very excited to use a lucky egg and quadriple the exp, but as I logged In I only found 100 pokemon in the bag (I have 450capacity).  Lvl.29. I want to die. And kill myself.

**Comment by terrylinooo** [comment]
Did you use your real account?
You can only use fake accounts for scanning.  If you turn on ditto mode. PokeAlert will catch common pokemons and transfer pokemons to Dr. for more space.

**Comment by PokeAlert** [comment]
@Cosfjinho @aaltaay You deserve what is happening to you guys.

PokeAlert has been developed by a handsome (:)) and enthusiast Pokemon trainer. Basically it is an nice alternative to PokeVision, an app to help you scan for Pokemon around you AND that triggers notifications when you are not using the app.

Before starting let's get the things straight. With PokeAlert you will be allowed to freely scan wherever you want. This means that if you scan YOUR location and then scan New-York or whatever REALLY FARE from YOUR location, it is an obvious sign of cheating and you will probably have your account banned.

With great scanner comes great responsibilities, be smart and just scan walkable or (drivable area). PokeAlert itself is very stealthy and respect a 10 seconds timeout between requests so if you scan responsively you should be safe!

DO NOT USE YOUR OFFICIAL ACCOUNT. Please create a separate Pokemon Trainer or Gmail account JUST for this app
