### ISSUE TITLE
Crashes and then keeps asking to add account

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#34]
When using background service it crashes after some time and then when I restart the app it keeps asking to add one or more accounts and spams this notification every few seconds even though I have 20 accounts added. To fix it I have to tap on Add Extra Accounts and then go back and manually statt the scan. But the problem reoccurs after a while. Also the background service stops scanning after some time.

**Comment by PokeAlert** [comment]
I have until now never managed to make the service crash. To fix this problem I need to find the root cause of the service crash, which is not normal.

I'm keeping this issue open even though it "might" have been fixed in version > 2.3.4 where I noticed some null pointers in the bug reports

**Comment by TFD777** [comment]
I think the problem was fixed because I no longer see it in 2.3.7.
