### ISSUE TITLE
Limit acconts/background scan

### ISSUE THREAD

**Issue by vmwinckler** [PokeAlert/PokeAlert#343]
I use 30 accounts, yesterday I verified that after 2 scans, everything disappears from the game. Just restarting the phone (or renewing the IP to work normally)

> Proxies for groups would be a Huge help as now ip is limited to 13 accounts before up ban so each group of 13 could have different ip

See more info in #330

**Comment by vmwinckler** [comment]
When setting a limitation of accounts to remedy the new situation, I suggest creating a "queue" where accounts are being used in a specific order thus generating more time in use between them.

**Comment by vmwinckler** [comment]
Maybe you have not expressed me correctly, my suggestion and add a limiter, of 11 or 12 accounts, for auto-scan, regardless of there are 200 accounts registered in the app, thus avoiding the IP ban.

**Comment by vmwinckler** [comment]
It seems like yesterday that niantic has emphasized IP blocking, some attitude needs to be taken, it is becoming impossible to use the app. My last alternative will be to exclude all accounts holding only 12, decrease the search radius and increase the search time to try to heal the locks.

**Comment by PokeAlert** [comment]
use 5 accounts for now

**Comment by formiga173** [comment]
Can only use 5 accounts in poke alert? By group or in total?

**Comment by vmwinckler** [comment]
5 accounts i lost a lot of pokemons... now i use 11..
