### ISSUE TITLE
Auto update doesn't work, ever.

### ISSUE THREAD

**Issue by afbakappeltaart** [PokeAlert/PokeAlert#348]
Hi,

Every time a new version gets out, it tries to auto update to the newest.
However, I can watch that update screen for over an hour without actually anything happening.
I now have to resort to manually looking up the apk and downloading it to install it over the current version, which gets a little tedious with 2 updates a week.
I already tried turning off the "unknown sources" setting in the android settings, but that didnt fix it.
Is there a way to fix this?

Best regards

**Comment by PokeAlert** [comment]
what android version do you have

**Comment by afbakappeltaart** [comment]
I have version 6.0.1

**Comment by PokeAlert** [comment]
works for me.

**Comment by afbakappeltaart** [comment]
Yea, it works for all around me except me :(
No, just the circle keeps spinning and it stays like that forever.
