### ISSUE TITLE
No timer for Seaking and probably some other pokemons

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#35]
The Seaking appeared with no timer. I cleaned the map and rescanned and the problem reoccured.
![screenshot_2016-08-12-22-59-00](https://cloud.githubusercontent.com/assets/12085708/17635640/3857add4-60e1-11e6-887a-2e2a26a96af0.png)
![screenshot_2016-08-12-23-06-26](https://cloud.githubusercontent.com/assets/12085708/17635687/7e44c0a2-60e1-11e6-9c30-04f75657f636.png)

**Comment by beejdrill** [comment]
I'm fairly certain that the pokemon that appear without a timer are the ones that have a negative TimeTillHidden value, which is believed to be a bug that applies to pokemon that stay more than the usual 15 minutes. Further discussion of spawn frequency and TTH bug here: https://www.reddit.com/r/pokemongodev/comments/4uuwx0/spawn_myths_debunked_aka_the_truth_about_spawn/

@TFD777 Just live with it for now, knowing that these pokemon are probably around for 30 or 45 minutes.

@demolina Read the above reddit post if more info is needed. Add a fix to handle these better onto your to-do list.

**Comment by demolina** [comment]
@beejdrill Sorry, I'm not involved with the developer team.

**Comment by PokeAlert** [comment]
@TFD777 

Yep I have verified and this is a kind of bug with PokemonGO server. For certain pokemon I do not receive (well -1) any timeTillHidden.

In version 2.3.0 I have written "Server returned no time" to be a bit more clear
