### ISSUE TITLE
Red circles only?

### ISSUE THREAD

**Issue by happy-420** [PokeAlert/PokeAlert#352]
My map only shows red circles and no Pokémons. I'm not sure how to fix this. Most if not all my accounts are okay and does not need to solve captchas. Any help?

![screenshot_2016-12-04-04-16-25](https://cloud.githubusercontent.com/assets/23740099/20861945/7877e3c0-b9d8-11e6-9537-4489833df677.png)

**Comment by Num1Phat** [comment]
The release notes say that all red circles is a very good indication that you have been ip-banned.

**Comment by happy-420** [comment]
Any resolution or tips as to how to prevent ip-banning? Currently I have 40 seconds for background scan interval, and all scan settings turned off.

**Comment by niqwilk** [comment]
Yea I can no longer complete a full scan without getting all red circles. Don't understand what changed with the new updates.
