### ISSUE TITLE
All mons transferred

### ISSUE THREAD

**Issue by ishaq4a** [PokeAlert/PokeAlert#353]
I used my main account with this app for an hour and now all my mons have been transferred. Is there any change I can get them back!!!! I know I know whats written on the main app but I made a big mistake.

**Comment by happy-420** [comment]
duuuuuuuuuuuuude

**Comment by xAryaStark** [comment]
I would lose all bowel control, for real 😖

**Comment by PokeAlert** [comment]
Big mistake indeed. Read more carefully next time
