### ISSUE TITLE
[Feature Request] Store and use valid expiration times to predict future expiration times

### ISSUE THREAD

**Issue by dripdropper** [PokeAlert/PokeAlert#356]
**Background**
PokeAlert no longer shows expiration times because Niantic no longer sends a valid expiration time until ~90 seconds before a Pokemon despawns.  However, if the same area is repeatedly scanned over time, it is possible for PokeAlert to show correct expiration times.  This is already implemented by a PR to PokemonGo-Map (https://github.com/PokemonGoMap/PokemonGo-Map/pull/1530), and it works perfectly in my experience.

**Algorithm**
If I'm reading the code for the PR correctly, the algorithm is very simple:
1. Whenever the server sends a valid expiration time (e.g. ~90 seconds or less) for a spawn point, store the expiration time (minutes and seconds) in a database along with the spawn point.
2. The next time a Pokemon is encountered (with a currently invalid expiration time) at a spawn point that exists in the expiration time database, the expiration time can be computed as the same minute & second as the database time within the next hour.

You can use the current system ("Over 1 minute") for any spawn point not yet in the expiration time database.  As you repeatedly scan an area and discover more valid expiration times, you gradually learn the despawn times of all spawn points in the area.  With a sufficiently high scan rate, you could learn most of the despawn times within a number of hours.

I believe this wouldn't be too difficult to implement, and I think it would make this great app even better!

**Comment by torantal** [comment]
+1

**Comment by dripdropper** [comment]
Depending on how the app is written, this algorithm should be relatively easy for @PokeAlert to implement.  Here is complete pseudocode that should make this work:

```
onFoundPokemon(serverExpirationTime, coordinates)
    currentTime = getcurrentTime();
    if isValid(serverExpirationTime)  // Within 90 seconds of despawning
        database[coordinates].time = serverExpirationTime;
        displayExpirationTime = serverExpirationTime;
    else if isValid(database[coordinates].time)  // Predict despawn time
        displayExpirationTime = database[coordinates].time;  // Use the stored minutes/seconds
        displayExpirationTime.hour = currentTime.hour;  // But use the current hour
        if displayExpirationTime < currentTime  // If the despawn time crosses the 60-minute boundary of the current hour
            displayExpirationTime.hour = displayExpirationTime.hour + 1;
    else
        displayExpirationTime = unknown;

    return displayExpirationTime;
```

**Comment by dripdropper** [comment]
We can estimate how many scans are required for this simple algorithm to find despawn times:
Since Pokemon despawn once per hour, each scan has a (90 s) / (3600 s) = 2.5% chance of finding a spawn point's expiration time.  Assuming a random distribution of scans, we can estimate the probability of finding an expiration time after _n_ scans to be:  1 - (1 - 0.025)<sup>_n_</sup>
If my mathemagics are correct, the algorithm should:
- Find the expiration times for 50% of the spawn points after 28 scans
- Find the expiration times for 75% of the spawn points after 55 scans
- Find the expiration times for 90% of the spawn points after 91 scans

**Comment by PokeAlert** [comment]
@dripdropper 
"Since Pokemon despawn once per hour" there is a big % than despawn every 30min

**Comment by dripdropper** [comment]
The algorithm handles all despawn times (currently, 90% at 30 minutes and 10% at 60 minutes).  Even Pokemon that spawn for 30 minutes appear at the same time every hour and disappear at the same time every hour.  For example, a spawn point near my house is active from :21 to :51.  This is a 30 minute spawn point, but it always despawns at :51 minutes past the hour.

**Comment by PokeAlert** [comment]
Added to version 4.0.12-5 👍
