### ISSUE TITLE
Very high battery and data usage

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#36]
I've noticed that this app is sending and receiving tons of packets which cause a very high battery and data usage. I am using background service with 10s delay, I know that I can increase the delay but I think the app shouldn't consume that much. Maybe you should make that the icons and scan area circles and other images would be saved in cache and then taken from there if needed (if it isn't done this way yet). We should find a way to make it more efficient.
![screenshot_2016-08-13-18-59-30](https://cloud.githubusercontent.com/assets/12085708/17644187/c6dd9698-6188-11e6-8a76-896c90e9bea1.png)
![screenshot_2016-08-13-18-59-19](https://cloud.githubusercontent.com/assets/12085708/17644188/cc1e553e-6188-11e6-8f96-0c09371edf04.png)

**Comment by PokeAlert** [comment]
Hey I have identified a potential cause for this I will push an update for vesion 2.3.6
