### ISSUE TITLE
Ditto IV over 82% ?

### ISSUE THREAD

**Issue by vmwinckler** [PokeAlert/PokeAlert#361]
I monitor the university all day where I work in search of a Ditto with high IV but, despite finding many, no more than 82%, I have found that there are always many pigeys, rattatas and zubats with IV fail. So I ask you if Dittos algorithm, when it fails to capture, sends another account, to make an attempt with a stronger pokeball.

**Comment by hkcheong** [comment]
i was found 95.6iv by PokeAlert two times,and  91iv 3 times,PokeAlert really work with high iv Ditto

**Comment by PokeAlert** [comment]
@vmwinckler theres is much I can do. there is no "send account x to y" because they will get speedcapped
