### ISSUE TITLE
All accounts are red (Speedcapped issue)

### ISSUE THREAD

**Issue by m0ol** [PokeAlert/PokeAlert#362]
Anyone have the same problem? how to solve this?

**Comment by dripdropper** [comment]
You are most likely experiencing a soft IP ban.  From the release notes:

>if you see ALL the circles red for more than 1 or 2 minutes --> your IP is most certainly soft banned (simply restart your router or turn off and the on the Flight mode to get a new IP)

You can also wait for the ban to expire.  You should try lowering your number of accounts or increasing the scan interval to avoid future bans.
