### ISSUE TITLE
Maximo de Accounts

### ISSUE THREAD

**Issue by formiga173** [PokeAlert/PokeAlert#363]
What is the maximum number of Accounts that can be placed in pokeAlert? 
I created 78 I am with 7 different areas plus the accounts do not load all just a few, I would like to know what is the limit of the accounts and how many accounts by areas?

**Comment by Trinity343** [comment]
there is no limit to how many accounts can be loaded inside of PokeAlert.  There are many players who have hundreds available on their list. if not all are showing up, it may be possible that you've set a scan area somewhere and have forgotten it. 

do they all show up on the account list itself?

**Comment by PokeAlert** [comment]
there is no limit, the limit will be your phone memory
