### ISSUE TITLE
Solve Captcha problem

### ISSUE THREAD

**Issue by marver89** [PokeAlert/PokeAlert#364]
Hello Guys.

after the last couple of updates i recently got some problems or atleast it started there.

At first when i start to scan it works perfectly but after 5 minutes my accounts starts to say Solve captcha and then the next comes within a couple of minutes and so on till i have to solve all accounts. 
but when i solve again then its just starts over from begining with the same problem and i have to solve again..

anyone know what i am doing wrong? :-)

**Comment by torantal** [comment]
It's just Niantic being good at successfully identifying bot behaviour. Play with the settings (more accounts, stealth, range, interval) to see what works best for you.
