### ISSUE TITLE
Show pokemon cp?

### ISSUE THREAD

**Issue by AbeFB** [PokeAlert/PokeAlert#366]
Is it possible to input our trainer level and show what cp that pokemon would be for us?

It's annoying when a dragonite pops up, I drive 1.5 miles to get it and it's 49 cp. 

Thanks for reading! :)

**Comment by torantal** [comment]
I'm pretty sure CP is the result of an individual dice roll, while IV will be the same for all. Therefore there's probably no way to predict.

**Comment by macinmn** [comment]
CP (level, basically) of the mon is the same for all players of the same level which encounter it.  I don't believe this has been RE'd.

**Comment by GTekes** [comment]
CP is fixed per mon, if you have it's record and the trainers lvl, you can calculate the CP

**Comment by PokeAlert** [comment]
No it is not possible. You cannot "just input a trainer level"
What you need to input the is the user/password of a trainer with a high level enough
