### ISSUE TITLE
Transferring Rares to the Professor

### ISSUE THREAD

**Issue by Sgt13Echo** [PokeAlert/PokeAlert#367]
Why does your app transfer rares and hatched eggs automatically to the Professor?  Could you please make it so that it keeps the Pokemon instead?

**Comment by lenghoo** [comment]
Hello,

Me Too, i lost all my best pokemons with the latest version of pokealert, it's clearly game over for me...

The risk known when using the main account was the risk of getting definitely banned by Niantic, nothing about transferring all the favorites pokemons.

Why suddenly this choice ?

Thx

**Comment by torantal** [comment]
This is a result of turning on Ditto mode. The app needs to catch commons to see if they are Dittos and to make room it will send Pokemon to the Professor.

Do NOT use it with your main account, you WILL loose your catches and possibly get banned.

**Comment by torantal** [comment]
Also, do read the documentation sometime...

https://github.com/PokeAlert/PokeAlert/blob/master/README.md

**Comment by lenghoo** [comment]
Never used ditto mode, but only real player simulation.

I used every new versions of pokealert for the past few weeks, never had this problem before the latest version 4.0.7, and every time I read the changes list. Nothing mentionned here, no warning :
https://github.com/PokeAlert/PokeAlert/releases 

Plus, transferring pokemons where as there's still a lot of room for new pokemons, and transferring favorite protected ones before all the pigeons is a really strange impression of a real player... or it imitates a really stupide one ! lol

It's totally fine for me to stop playing if I'm banned by Niantic, but i never thought it would end this way...

**Comment by torantal** [comment]
As it's written in the readme:

> Real Player tries to simulate 'natural behaviour of player' (Pokestop spinnning, Pokemon catching, Item transfers) **(Warning!!! Real Player is interfering with your account! Pokemons and items are being transferred in order to make space for new ones!!)**

**Comment by lenghoo** [comment]
I know, all I'm saying is that it's a completely new behavior appeared in the latest version of pokealert, but there was no warning about it in the new features list. 

No one can read all the documentation for each new hotfix downloaded.

**Comment by PokeAlert** [comment]
@lenghoo no excuse mate, there was warning everywhere. you simply didn't read. Consider that as an expensive lesson.

**Comment by Sgt13Echo** [comment]
Can you turn the transfer off?  Many of us have second accounts to catch rares if they run on us in our primary account and to transfer Dragonite over a Ratta to make space makes NO sense!
