### ISSUE TITLE
(ISSUE) Telegram External notifications not woking(Ditto)

### ISSUE THREAD

**Issue by hkcheong** [PokeAlert/PokeAlert#368]
I'm using PokeAlert-4.0.7-3 , 
I found that Ditto does not working on External notifications (Telegram), when i click the link on telegram(Ditto),everything show N/A,and can not correctly display google address

ex:
http://www.pokealertapp.com/poke/index.html?info=eyJhdHRhY2siOjAsImRlZmVuc2UiOjE0LCJsYXQiOjIyLjMyNTg3MDkwNjM2NTUxMywibG5nIjoxMTQuMjE4MTA1OTQyOTAyMTcsIm1vdmUxIjoidGFja2xlIGZhc3QiLCJtb3ZlMiI6ImFpciBjdXR0ZXIiLCJuYW1lIjoi55m+6K6K5oCqIiwic3RhbWluYSI6MTAsInR0aCI6IiJ9

**Comment by PokeAlert** [comment]
This is due to the language. You are using chinese. and for some reason the string cannot be decoded.

**Comment by PokeAlert** [comment]
@hkcheong  Its now fixed, please try PokeAlert 4.0.7-5
