### ISSUE TITLE
Feature Req:  option to select team or warning for teamless player when Gym Encounters enabled

### ISSUE THREAD

**Issue by macinmn** [PokeAlert/PokeAlert#369]
I know this is ultimately my fault, but I had a L27 teamless I had been working on for several months along with a few other 20-somethings which are all now Team Mystic.  When I enabled the gym info setting, it didn't dawn on me that you have to have a team in order to see Gym residents, which obviously in hindsight makes sense.

A warning when the option was turned on, or a prompt to select team for a teamless player would have been helpful in avoiding this.

pretty darn useful app though, thanks.

**Comment by PokeAlert** [comment]
hmm hang I dont understand. It is not normal your account doesnt have a team.
Did you enable ditto mode or real player? Normally if the account is > that lvl5 it will choose blue team

**Comment by macinmn** [comment]
yes, any player account I have in the app that used to be neutral, L5-L27 is now Mystic/Blue.  my settings are on for everything (Ditto mode, Real player, Show Gyms, Retry Speedcapped), except multi area and show timer.

so you're saying "real player" mode means 'real human behavior', and not 'real device simulation'.  I presumed the latter, and that the issue with picking team was related to the gym feature.  If that's the case, this suggestion should be for adding an explanation to the Real Player setting more for what it does (now that I know the term means 'behavior' I am turning it off as I can't expect to know what else it's doing, transferring mons, etc).  I still think a choice on team would be a good idea as well.  Thank you for the explanation here though.

**Comment by PokeAlert** [comment]
There is enough explanation on the github + chan + website

**Comment by macinmn** [comment]
obviously not
