### ISSUE TITLE
(Question/Quesedillia) eMail verification for GMAIL required? Why? 

### ISSUE THREAD

**Issue by HELLspawnTIM** [PokeAlert/PokeAlert#370]
All my 20 scanning accounts are created via the PokeAlert internal batch account creator "roboto" 
I used an new fresh GMAIL eMail Account and entered the same password which I used for the GMAIL eMail account itself. 
After ~3days all my scanning accounts (even if unused until then) are failing because of "eMail verification required" 
I thougt this should not happen because we are using GMAIL accounts, as explained by the "roboto" 
Why is that and how to avoid that?

**Comment by PokeAlert** [comment]
You still need to verify the account by clicking on each link...

**Comment by HELLspawnTIM** [comment]
That should be made clearer in the App, as I did assume different
