### ISSUE TITLE
Suggestion: account selection screen for background scan

### ISSUE THREAD

**Issue by piotrrr** [PokeAlert/PokeAlert#373]
Is it possible to add the account selection screen like the one that pops up when you start a single scan to the background scan?

I have like 15 accounts loaded to the program and when i start the background scan i get soft bans very often cause the program uses all of the accounts. If i could select for example only 10 it would solve this issue i think.
Correct me please if it's already possible to assign only some of the accounts to the background scan.

**Comment by PokeAlert** [comment]
yep will be done
