### ISSUE TITLE
4.0.7-8 Account creation issues

### ISSUE THREAD

**Issue by coryallegory** [PokeAlert/PokeAlert#374]
The account creation tool ends up in an infinite loop with no accounts created, steps to reproduce:

User chooses creation option, enter account password, email, number of accounts to create (eg. 1). Select CREATE.
App presents a fullscreen ad, dismiss by tapping the X.
App presents Data of Birth and Country selection screen.
User presses the Continue button on the displayed Pokemon Trainer Club page.
`***
App presents I'm not a robot screen, check box.
Re-captcha displayed, solve re-captcha.
Select Continue.
App displays loading icon, then repeats infinitely back at ***

No accounts are created, no activation emails received, etc. Running Android 7.0 on a Nexus 6

**Comment by KS71** [comment]
I have the same problem one OnePlus 2, Android 6.0.1

**Comment by coryallegory** [comment]
Confirmed fixed by version PokeAlert 4.0.8-2

Thanks for the really quick updates @PokeAlert !
