### ISSUE TITLE
cant find pokemon anymore

### ISSUE THREAD

**Issue by Dragonsoule** [PokeAlert/PokeAlert#38]
Well i can't use the service anymore it's simply not working.

**Comment by TFD777** [comment]
There is a possibility that all of your accounts got banned. You should test them in other apps, that require PTC login.

**Comment by Dragonsoule** [comment]
Okay thanks

**Comment by PokeAlert** [comment]
Hi @Dragonsoule @TFD777 is right this must be the cause. in PokeAlert >2.3.1 I have displayed a message when an account is banned
