### ISSUE TITLE
4.0.8-2 Multiple Account Creation redirects to "forgot your password" on PTC Site.

### ISSUE THREAD

**Issue by chr2002qw** [PokeAlert/PokeAlert#380]
Account creation worked fine in previous versions.

But now, the Account Creation redirects to the Forgot password Site on PTC because bad cookies or so are stored in the in App Browser.
I think, something changed in the inapp browser due to this new massive ad-crap :-(

Ads are ok, but should not render the app funktions useless.

**Comment by GitBraK** [comment]
I can confirm this issue. With the recent ban wave I have gone to make more accounts under three emails and had this show up by the second account on each.

**Comment by gazza1988** [comment]
I think it is to prevent people having multiple accounts on the same email address. It appears to me to be a pokemon.com thing. Once you try creating an extra account it detects you already have an account and goes to the password recovery screen. 

There is a Gmail trick where you can put a "." anywhere in the email address and it still goes to the same email account. Websites see it as a completely different email. 

Say example@gmail.com is your email address. Entering example@googlemail.com, ex.ample@gmail.com e.x.a.m.p.l.e@gmail.com etc etc all go to the example@gmail.com address

Could this be coded into pokealert for multiple accounts?

**Comment by PokeAlert** [comment]
please can people start reading and using @outlook?

thanks
