### ISSUE TITLE
External notifications re-send on each scan

### ISSUE THREAD

**Issue by mvdiener** [PokeAlert/PokeAlert#381]
It appears that an external notification (I'm using discord currently) is sent every time a pokemon is found, instead of just the first time. When running continuous background scans, this leads to a lot of duplicate notifications and is hard to tell what is a new find or not. Would be great if it functioned like the notifications on mobile, that it alerts you only on the first time a pokemon is scanned/found.

**Comment by fluke98** [comment]
I got 9 notifications for the same mon

**Comment by PokeAlert** [comment]
in a row? or because a different account scanned the same mon?

**Comment by spishee** [comment]
@PokeAlert both of it I confirm too. in a row and differ account.

**Comment by mvdiener** [comment]
It appears that any time any account scans the same pokemon (meeting your filter criteria), an external notification is re-sent. I can't confirm whether this is the same account every time, but when the little blue scan circle hovers over that pokemon, another notif. is sent. Perhaps some of the same logic in place for notifications on mobile (only notifies on first time found) could be put in place here? Not sure how your code is structured.

**Comment by febs** [comment]
I confirm this.

**Comment by PokeAlert** [comment]
Fix in 4.0.9
