### ISSUE TITLE
Account Ban

### ISSUE THREAD

**Issue by Arzts** [PokeAlert/PokeAlert#382]
starting from update 4.0.7-8, i have 20 accounts banned in one day. can i know what is the issue here that caused the banning? before this all my 20 accounts worked just fine.. my friend's pokealert also have the same issue. Thx.

**Comment by arhi3a** [comment]
Answer is simple Niantic Ban Wave

**Comment by Larry1977** [comment]
I was banned too today. I think ditto mode is doing it. It's catching too many common Pokemon, spinning pokestops and deleting pokemon to make room for more common Pokemon. It's also leveling me up too fast. Was up to level 20 with hardly any Pokemon in storage after playing for around a month.

**Comment by Arzts** [comment]
but i didn't open ditto mode.. FML i'm so unlucky 20acc banned in 1 day.. T^T

**Comment by PokeAlert** [comment]
Ban ban ban
just create new ones thanks
