### ISSUE TITLE
Fastscan not showing mons

### ISSUE THREAD

**Issue by rdthp** [PokeAlert/PokeAlert#383]
First of all, fast scan is beautiful beyond words. My friends and i had a pretty elaborate system of covering our neighbourhood by distributing streets to different individuals.Then we would manually share in our group if something good popped up.

Fast scan lets us see each others scans right there on our own screens!

But for the last 10hrs we cant see anything on it. I can only see the mons in the area my background scan is covering. Did something happen?

Thank you so much for everything you've done so far. With this new tracker the game is unplayable without PokeAlert.

**Comment by PokeAlert** [comment]
Fast scan depends on server load, if no mon either not scan were done there or server down
