### ISSUE TITLE
Option to not transfer hatched eggs!

### ISSUE THREAD

**Issue by Sgt13Echo** [PokeAlert/PokeAlert#384]
In order to make my account seem more real I actually log inr a few and put eggs into incubators.  But your app transfers all of them. Can you provide an option not to transfer eggs or only transfer 2k eggs/Common Pokémon?

**Comment by arhi3a** [comment]
I think u spent more time to make that acc 'seem' real than it's worth it. It's faster to create new one than putting eggs into incubators. And we are still using old API so Niantic knows it's either map/bot

**Comment by Sgt13Echo** [comment]
really? when trading comes out I would love to trade the nice hatches!

**Comment by arhi3a** [comment]
To that moment all your PA accounts will be probably banned. + PA is not a botting app+ everything hatched from your eggs would be transfered any way.
