### ISSUE TITLE
Multiple account?

### ISSUE THREAD

**Issue by inu20** [PokeAlert/PokeAlert#39]
Hello team PokeAlert, this is Anne from Taiwan...
This is really helpful app, I really love it~^ ^

I just wondering how to use multiple account make scan faster.
Mine is Google acc, I create a PTC acc for PokeAlert.
PTC acc stay at same place, nomatter where I go PokeAlert will alert the pokemon at that place(this another problem I would like to ask)...
All I need to do is create another PTC acc?
If those PTC location are at same place, will they still work?

**Comment by TFD777** [comment]
Hi, yes you need to create more PTC accounts and I would suggest you to start background service because it will always scan around you even if you move.

**Comment by inu20** [comment]
Got it! Thanks for reply~ Help me a lot! ^^

**Comment by TFD777** [comment]
@inu20 You're welcome.^^

**Comment by PokeAlert** [comment]
Hey! Thanks @TFD777 !!!
