### ISSUE TITLE
Create default filter to apply to all pokemon

### ISSUE THREAD

**Issue by Marciobds** [PokeAlert/PokeAlert#393]
It would be nice to be able to create a filter (like the individual we have for each pokemon) and have an option to apply it to all pokemon.

For example, a filter to notify for pokemons with IV >= 90% and show them on the map, and apply this filter to all pokemon, only to rare one, or other kinds of categories of pokemon.

This would make filtering a lot easier as we would not need to edit every individual pokemon, just make some adjustments on the ones we do not want to be an exception to the filter we created. Or if we combine 3 or 4 of this filters we could adjust all pokemon without the need to open every and each one of them.

**Comment by arhi3a** [comment]
Long press on pokemon in filter management tab and select as many pokemons as you want than long press on one of them and click on advance filter all changes are going to be applied for all selected pokemons.

**Comment by Marciobds** [comment]
Thanks.
