### ISSUE TITLE
Tracker hang up

### ISSUE THREAD

**Issue by GTekes** [PokeAlert/PokeAlert#397]
PokeAlert worked fantastic until i changed the scan frequence, increased for to reuce captchas and activated real player mode. From there on, PA wouls scan always the same spots, trying to create new accounts gave me a blank screen and after deleting and reinstalling the app, map is blank and google search returns: impossible to load research results.
I use a BLU Dash 5.0 with Android 4.4.2.
It worked for +- 48hours.  

SOLVED, User sided error

**Comment by GTekes** [comment]
Solved: My cell fone had the wrong date and time and that for, Google services used by Poke Alert wouldn't work!

**Comment by vlalo001** [comment]
@GTekes please push the "Close" button to close this issue, as you have solved it
