### ISSUE TITLE
App crashes after last update

### ISSUE THREAD

**Issue by japscf** [PokeAlert/PokeAlert#40]
Hello, Pokealert team. I'm really enjoying the work that you are doing, and is helping me a lot. Loving this app :D
But, after the latest update(2.3.2-2), the app closes when it begins to scan around with background auto scan on zenfone 2.
You could try to fix it?

**Comment by TFD777** [comment]
Open the app, start the background service and press the home button. Do not close the app from recent apps tab and it should work.

**Comment by PokeAlert** [comment]
Hey!

for version 2.3.2 I have updated a package that causes problem with Android 5 (Lollipop) this is now fixed in version 2.3.5-5
