### ISSUE TITLE
External notifications - Browser doesn't show Pokemons on Google Map anymore.

### ISSUE THREAD

**Issue by Fonzzz** [PokeAlert/PokeAlert#405]
I really love this feature. I instantly created a Telegram-Channel and so on when it was released. 

But when people try to click on the link (to see where the pokemon is located) provided by the Telegram-Notification it doesn't show the map anymore but instead the google frontpage which made this feature entirely useless. Please fix it I can't live without it :( . 

Thanks for your work.

**Comment by HELLspawnTIM** [comment]
I had the same issue only Happening when the default Browser was NOT started before clicking the link

Did you try to go back once an click the link again?

**Comment by PokeAlert** [comment]
before clicking the map link you need to WAIT the page shows the pokemon name
