### ISSUE TITLE
App UI is messed up

### ISSUE THREAD

**Issue by nadermwb** [PokeAlert/PokeAlert#41]
My app Ui is messed up as shown on the pic as the start scan is on top of the relocate of the map my mobile is xperia Z5 premium dual sim
![screenshot_20160816-113011](https://cloud.githubusercontent.com/assets/20982565/17694690/bc1273ce-63ad-11e6-8eb3-7bb44fbf68bd.png)

**Comment by PokeAlert** [comment]
Hey!
Thank you for the bug. 
This is caused by the fact that you have an AdBlocker and that I have indicated to the button the be placed "above" the bottom ad bar (which in your case is invisible)

If you need a quick fix, turn off the adblocker. 
I have put this issue on my todo list
