### ISSUE TITLE
Request non-stop scan feature

### ISSUE THREAD

**Issue by spishee** [PokeAlert/PokeAlert#410]
Please add more option for non-stop scan in area for each IDs assign. by now they need to restart after cycle finnished.

**Comment by Mitarexia** [comment]
You just push the "radar" button to start the background service, that will constantly scan an area.

**Comment by spishee** [comment]
Currently PA waiting for circle scan to finished before make a new scan. I wish PA make a scan continues without waiting circle scan finished.

**Comment by PokeAlert** [comment]
thats gonna kill ur accounts
