### ISSUE TITLE
[Enhancement] show moves in external notification

### ISSUE THREAD

**Issue by dingo0410** [PokeAlert/PokeAlert#413]
Thx for supporting external notification for telegram. It’s good to show up iv and atk, def, sta stat. However, it would be great if it can notify the moves as well. 

Also, it would be more convenient for user to click link that show up the google map directly, instead of click the pokealertapp.com link. See if you would like to adjust,or at least shorten the length of pokealertapp.com. 

Thanks!

**Comment by HELLspawnTIM** [comment]
The external notification link already shows the movesets. If it does not for, you should check your filter and Settings 

Example:
http://www.pokealertapp.com/poke/index.html?info=eyJhdHRhY2siOjksImRlZmVuc2UiOjIsImxhdCI6NDkuNDIyNTIzMjMxMjkxNTgsImxuZyI6OC41Mzc4NzQ3NTA2Mjc5NTUsIm1vdmUxIjoid2F0ZXIgZ3VuIGZhc3QiLCJtb3ZlMiI6Imh5ZHJvIHB1bXAiLCJuYW1lIjoiVHVydG9rIiwic3RhbWluYSI6MTMsInR0aCI6IiJ9

**Comment by SoldierSnakie** [comment]
There must be a couple reasons that Telegram bot sends you a redirect pokelalert page. Yes, it would be very useful if it sends you google map page or send ubication directly from Telegram, maybe for donators(?) just saying...

**Comment by dingo0410** [comment]
Yes, the moves are shown in redirect link of pokealert already, but not show up in telegram and like this:

水箭龜 20% (5/2/2) http://www.pokealertapp.com/poke/index.html?info=eyJhdHRhY2siOjUsImRlZmVuc2UiOjIsImxhdCI6MjIuMzMxMzQ4MjA2NTMxMDg2LCJsbmciOjExNC4xOTAwNTU0MjUwOTY1MywibW92ZTEiOiJiaXRlIGZhc3QiLCJtb3ZlMiI6ImljZSBiZWFtIiwibmFtZSI6IuawtOeurem%2BnCIsInN0YW1pbmEiOjIsInR0aCI6IiJ9

**Comment by PokeAlert** [comment]
Doe in 4.0.11-1
