### ISSUE TITLE
Completely nuked my account, why is it so evil.

### ISSUE THREAD

**Issue by tcolar** [PokeAlert/PokeAlert#414]
Before you say, "hey moron you shouldn't use your real account", yeah I know and yeah it was a mistake, had added my real account originally and then created a dummy one which is what I had used until i accidentally selected the real one last Friday ... it ran for maybe a couple minute and didn't even catch anything but here is what it actually did in those 2 minutes:

- **dump all my raspberries** .. ok I didn't care hat much about that
- **transfer all but 35 of my 300+ pokemon**s !!!  WHY ????

Now here is what you warning make it sound like might happen:
"Warning : If your pokemon box is full it might start transferring pokemons", my pokemon box wasn't full: 330/400.

What it should say : 
**"Warning: his will obliterate your collection for no good reason".**

By the way I can't even figure how it decided which 35 pokemons to keep, or why 35, it didn't keep a single favorite, not a single over 1700 (I had maybe 40 over 2000),what it kept is a random assortment of only weak crap, No more Lapras, Muk, Dragonite, Snorlax, Gyarados for me, thanks, the best thing left is a 1700 Clefery with Dazzling gleam, thanks so much.

I know I made a mistake and I'm paying for it, but as a software dev myself I don't even understand what kind of absolutely careless algorithm could cause this kind of damage, unless it's intentional, I wish I could see that code ......

PSA: ditto mode was off, so don't blame it on that

**Comment by JoniValles** [comment]
" I wish I could see that code ......" IT'S OPEN SOURCE

**Comment by terrylinooo** [comment]
Transferring pokemons is for more spaces.
Dumping all raspberries is for more balls. 
What's the problem on you?

**Comment by PokeAlert** [comment]
" as a software dev myself"
that was the best part :)

**Comment by tcolar** [comment]
@JoniValles Where ? This repo only contains a bunch of XML translation files, the Readme says nothing about where that code for the actual app is. 

@terrylinooo 
`Transferring pokemons is for more spaces.` -> There was plenty of space.
`Dumping all raspberries is for more balls` -> There was plenty of space.
`What's the problem on you?` -> I just find it poor behavior to throw away everything when wasn't needed. Do you throw away everything that's in your wallet in the morning, just in case later you might find a dollar ? 

@PokeAlert : I know how to read and my whole point was exactly that, that your Readme make it sounds like pokealert is going to make space *when needed* or that it will act like a player would. It's very far from that and much more dangerous.
