### ISSUE TITLE
[Telegram] Issues with setting up notifications

### ISSUE THREAD

**Issue by Kidd74** [PokeAlert/PokeAlert#417]
Hey guys,

I'm trying to use the Telegram notification feature in order to receive Pokealert notifications on my iPhone. 
I simply typed the token the fatherbot gave me within the bot token field, and below I entered the name of my channel with a '/' at the beginning, so it looks like "/channelID".

Am I misunderstanding how to use this? 
Because I am not receiving anything within the Channel I created with my iPhone.

Thank you very much for your help, it would really help me during this great event right now!

**Comment by SoldierSnakie** [comment]
try @channelID. Your bot has to be administrator of the channel btw.

**Comment by brian-kujawski** [comment]
I'm having the same problem. Created new bot for use with PokeAlert, created new channel to share with friends, made bot an admin of channel. I've entered the bot token into PokeAlert, and have entered the @ChannelName as the channel ID.  No messages are ever received in the Telegram channel.

First time messing with Telegram, so apologies if I've missed something stupid, but any help would be appreciated.

**Comment by PokeAlert** [comment]
This is seems more like a question for telgram support. 
Try manually hitting the endpoint and see if the bot is correctly set up. If so and you think its a pa bug please feel free to reopen this
