### ISSUE TITLE
Invasive advertizing

### ISSUE THREAD

**Issue by SimonMoua** [PokeAlert/PokeAlert#419]
The Mobile strike ad is virtually immortal. I can't close it for the life of me, and when if finally closes, it restart in a loop. 
I don't know if you control which advertiser are on your ad, but it's ruining my experience to a point where I can't use the app anymore.

**Comment by brian-kujawski** [comment]
FWIW, I believe this was a bug within PokeAlert itself which caused the loop and I thought it was fixed in the latest update. Have you updated your app to the newest version already?

**Comment by CreativiTimothy** [comment]
Yes, 4.0.11-6 seems to fix this.
