### ISSUE TITLE
(Twitter) notification customization for areas

### ISSUE THREAD

**Issue by Agilo3** [PokeAlert/PokeAlert#420]
In my local community we are scanning 4 different areas which cover two cities. I'm sure the notification customization is being worked on, but I would like to ask for the possibility to also add a custom text to be pre-pended to the notification based on the area.

For instance: when you select an area and select the bots to be scanning that area, there could be a text field "notification prepend text" that could have a custom value, for example "City 1". Then when the tweet is sent out, it could read (for example):
"City 1: Squirtle 96% (13/15/15) tackle fast/aqua tail)"

This would be very helpful in determining which area the specific Pokemon was scanned in.

**Comment by arhi3a** [comment]
Naming areas, and customized notifications will be added later. 
Basicly what u suggested was already on his To-do list :D

**Comment by Agilo3** [comment]
Awesome! Thanks for informing me. :)

**Comment by PokeAlert** [comment]
If there is sufficient demand I can continue improving the external notification system. Unfortunately for now these requests are taking concerning less than the 1% of PA users

**Comment by Agilo3** [comment]
Including the area names is all our community really wanted(/needed). You've made a lot of people happy here! Thanks!
