### ISSUE TITLE
App only scans 20 areas at a time. Messes with despawn timers.

### ISSUE THREAD

**Issue by CreativiTimothy** [PokeAlert/PokeAlert#421]
I spent about 2 hours creating 73 very small areas that scan Dragonite and Snorlax spawn points because that is the most rpm-efficient. However, Pokelaert only scans 20 areas at a time which messes up the timers. My friend tried to drive to a Snorlax and it was not there. My rpm was at around 180rpm, and I had two hash keys of 150rpm equaling 300rpm, and it did not say the hash server was down, so I do not think it was a Pokefarmer problem. A couple others in the discord chat have confirmed this issue of 20 area limit. It's very annoying. I deleted my 73 circles and did 20 big circles and my rpm went to 750, so that did not help.

This issue and the inability to save locked areas is preventing me from donating. Thank you very much.

**Comment by PokeAlert** [comment]
its 20 max grey area

**Comment by CreativiTimothy** [comment]
@PokeAlert Yes, I know. But I feel like there is no good reason for the limit. It doesn't hurt you since you're not running any servers, it doesn't hurt Pokefarmer because it is based on rpm, not how many areas, and it doesn't hurt the algorithm either. I might re-open this issue later (by writing it again).
