### ISSUE TITLE
PokeAlert sometimes notifies same exact Pokemon twice

### ISSUE THREAD

**Issue by CreativiTimothy** [PokeAlert/PokeAlert#423]
What the title says. My areas are not overlapping, so that's not causing the problem. I am using the new API by Pokefarmer but the old API had the same issue. I'm not sure why it happens sometimes and not all the time

**Comment by PokeAlert** [comment]
Which version are you using

**Comment by CreativiTimothy** [comment]
4.0.11-6, but this has been for every single version that I have used so far

**Comment by CreativiTimothy** [comment]
4.0.12-1 (latest version) still has this problem

**Comment by Chris-Perkins** [comment]
Are you talking about the scanner finding the same Pokemon 30 minutes later? At that point the Pokemon spawn is determined as 60 minutes.

**Comment by PokeAlert** [comment]
I need to now this as well

**Comment by CreativiTimothy** [comment]
@Chris-Perkins @PokeAlert No I'm not talking about it. IT find the same Pokemon twice within 10-20 min timespan. And the app does not crash. This appears to be fixed in the Twitter feeds where TWitter does not let you tweet the same thing twice in a row, but I still get the notifications on my phone.

**Comment by PokeAlert** [comment]
This should be fixed now. please re open if not
