### ISSUE TITLE
[Bug] weight filter seems not work in telegram notification

### ISSUE THREAD

**Issue by dingo0410** [PokeAlert/PokeAlert#425]
Thx for adding weight filter in pokealert!! It’s work perfext in the apps and i can find the xs ratatte and xs fish easily.

But i found that the filter seems not work in telegram notification and it just notice all ratattes to me. Please fix.

Thanks!

**Comment by PokeAlert** [comment]
Ah yep forgot to add it there :)

**Comment by PokeAlert** [comment]
Fixed
