### ISSUE TITLE
Cannot perform consecutive scans

### ISSUE THREAD

**Issue by lmk3087** [PokeAlert/PokeAlert#426]
After I scan once, if I try to scan again afterward, nothing shows up. I have to restart my phone in order for a scan to work again. And then I have to restart my phone again . . . and so on.

Also, not certain if it is related, but every pokemon is shown as "0 meters" away from me.

Thanks for any help!

Best.

**Comment by Chris-Perkins** [comment]
Can confirm I get this same problem. My phone is a Samsung Galaxy S4 if it helps any.

**Comment by PokeAlert** [comment]
@lmk3087 I need more info.. App version ? Android version? Quick scan? Background scan? Fixed area? etc....
For the 0meter thing it just means you GPS is not working and / or not correctly sending the location to the app.

**Comment by lmk3087** [comment]
Sure! Yea, thanks for the help. Sorry for not posted initially, I was unaware that information would be needed.

In order:
App version - 4.0.11-6
Android version - 6.0
Quick Scan specifically (though I have been trying with background scans and am uncertain, don't have enough data yet)
Non-fixed area

Also, a note, I only started noticing this issue when scanning a large number of accounts (on the order of 100+).

As for the 0 meter thing, hmm. So, I guess in a different question, any ideas on how to fix this issue, or is the question too broad? I have noticed after a scan, I also have to restart my phone before PoGo will pick up my GPS location as well.

Thanks for any input/help you may have.

Best.

**Comment by PokeAlert** [comment]
I'd suggest first to update to the latest version 4.0.12-3 and see if it happens again

**Comment by lmk3087** [comment]
Okay, I have updated to the latest version and done several scans and have noted my findings. There definitively does seem to be some issue. The best way I can put it, it is almost like the scanner hits a cap.

I can do several small, non-fixed, quick scans without any difficulty. However, if I try even two large scale (on the order of 2000m) quick scans, the second one always seems to fail. It looks like it is scanning, though much faster, and turning to red circles quite quickly, and nothing is showing up. I am using Paras (a plentiful pokemon in my area) as a control, and even they do not show over the large second scan of ~2000m.

As potential further proof of my theory, when I do even 1 larger quick scan (~2800) the scan seems to quick about halfway. The new system seems to start from the center of the scanning area, and work its way outward. Not a single pokemon will show in the out 1/3 of a ring, as if it has just stopped somewhere along the way.

I have also tried this with the background service and gotten strikingly similar results. It seems as if the service just does not make it to all the areas I have locked down to scan. More so, if I stop a background scan, and the start it again, the scanner does not pick up anything at all, even my control Paras, much like the quick scanner.

That is all the information I have currently, but if there is anything else you need, please let me know, and I will do my best to help.

Best,

**Comment by lmk3087** [comment]
Also, regardless, thank you for everything.

**Comment by PokeAlert** [comment]
Send me some logs (discord channel) of this

**Comment by coryallegory** [comment]
@lmk3087 do you have your settings set to catch pokemon for IV or ditto etc?

I have been getting IP banned extremely quickly since at least version 4.0.11 with around 35 accounts on background scans or quickscans. Even using fewer accounts. This is also about the time I activated IV filtering as well. I'm pretty mindful of triggering speedcaps so I don't think it's related to suspicious jumping around the map or short timeframes between scans.

**Comment by coryallegory** [comment]
Just did a few experiments w 56 accounts. No ditto or IV filtering runs fine without issues, reaches ~320 rpm at times. Stop, new IP 10 min later, turn on IV and I get IP banned after approx 5 mins of background scanning, reaches just over 400 rpm at times.

**Comment by coryallegory** [comment]
That was v4.0.12-7, Real Player enabled, Retry disabled, 10s interval.

**Comment by coryallegory** [comment]
Hm few more runs and IV checks (catching the pokemon) are not the trigger. I don't know how there are people managing to successfully scan with 1000+ accounts ha.

**Comment by PokeAlert** [comment]
They have good internet connections
