### ISSUE TITLE
Advertisements keep crashing the app

### ISSUE THREAD

**Issue by AlexWake** [PokeAlert/PokeAlert#428]
Whenever I pull up PokeAlert on my Galaxy S7 it will open normally, but 90% of the time, if I tap anywhere on the screen like the menu to try to scan, it pulls up a Mobile Strike ad and constantly reopens it till it crashes the app. Makes scanning near impossible for me. Is there any way to fix this?

**Comment by PokeAlert** [comment]
What version of PokeAlert are you using?

**Comment by AlexWake** [comment]
Was using the 4.0.12-2 version but I just I just updated to the 4.0.12-3 one and that seems to be working fine now.
