### ISSUE TITLE
2captcha doesnt work properly

### ISSUE THREAD

**Issue by SoldierSnakie** [PokeAlert/PokeAlert#431]
My account arent solving captchas and never did, account balance is always the same (5$) and sometimes i get an email from 2captcha saying my account is limited because of the following errors:
> ERROR: 1003
You are getting ERROR_NO_SLOT_AVAILABLE because you are uploading many captchas and server has a long queue of your captchas that are not distributed to workers.
You received three times more errors than amount of captchas you sent (but not less than 120 errors).  Increase the timeout if you see this error.
ERROR: 1004
Your IP address is blocked because there were 5 requests with incorrect API key from your IP.
ERROR: 1005
You are making too many requests to res.php to get answers.
We use the following rule to block your account: R > C * 20 + 1200
Where:
R - the amount of your requests
C - the amount of captchas you've uploaded
That means that you don't have to make more than 20 requests to res.php per each captcha.
Please remember that balance request sent to res.php also counts!

I thought it was as simple as create a 2captcha account, deposit more than 4$ and put the api key on PokeAlert.

**Comment by PokeAlert** [comment]
Maybe they are busy. PokeAlert brought them a HUGE amount of new captcha to solve :)

**Comment by SoldierSnakie** [comment]
2captcha is now working without problem
