### ISSUE TITLE
How can I peform normal scans in verson 4.0.12-7?

### ISSUE THREAD

**Issue by LegornSunrise** [PokeAlert/PokeAlert#432]
Greetings.
How can I peform normal scans in verson 4.0.12-7?
Whe I try a quick scan, it only last 10 sec, and I have to click it all the time.
When I try background scan it doesn't work.

**Comment by arhi3a** [comment]
Backup your accounts and filters, unistall old app. And than install this one: https://github.com/PokeAlert/PokeAlert/releases/download/4.0.12/PokeAlert_4.0.12-10.apk
and import your accounts/filters
