### ISSUE TITLE
New way to highlight pokemon in GUI

### ISSUE THREAD

**Issue by edwardwong80** [PokeAlert/PokeAlert#440]
When I see notification, I click on that, PokeAlert will bring me to the map location where the pokemon is, but there is no highlight on that particular pokemon. Imagine I am looking for IV 100% Rattata, and you know there could be like 10's of them around, right now I have to click in every rattata nearby to find out the one I want. Is there a good way to highlight them? May be circle them out, or changing it's color, anything that can show it differently will do.

**Comment by HELLspawnTIM** [comment]
How about filtering all Rattata to show to >90 percent? 
Then there will be only Rattata shown which you are interested in obviously?

**Comment by RezzZ** [comment]
if you have external notifications you will get the exact location pinpointed on googlemaps as well. Bit of a workaround though, HELLspawnTIM's idea is much better :)

**Comment by PokeAlert** [comment]
@edwardwong80 I note the feature
