### ISSUE TITLE
(Feature Request) IV Filter

### ISSUE THREAD

**Issue by Ayron88** [PokeAlert/PokeAlert#442]
I was wondering if you would be able to add an IV filter for Pokemon Go. I love the PokeAlert app but i find myself having to go to PokeSensor to use thier IV Filter. I like to be able to only see the 90% or higher IV at times.

**Comment by HELLspawnTIM** [comment]
Is already implemented since weeks
Read the user guide please

**Comment by arhi3a** [comment]
actually i think it's in app for months already.

**Comment by RezzZ** [comment]
Is it also possible to set a general filter for IV? I know you can set it per pokemon but not as a global setting for all pokemon.

**Comment by arhi3a** [comment]
Just long press on one of pokemon names in filters than select all pokemon you want to apply setting and then one more time long press and open filter options :D

**Comment by RezzZ** [comment]
sneaky feature :), love it

**Comment by stekkedecat** [comment]
if issue is solved, please also close!
