### ISSUE TITLE
Make use of lucky egg automatically?

### ISSUE THREAD

**Issue by edwardwong80** [PokeAlert/PokeAlert#443]
In Ditto mode PokeAlert will catch 4 pokemon type to test a ditto, results in trainer level up after certain time. Lucky egg will be granted when trainer reaching certain LV. Right now I know that PokeAlert will throw again the eggs, not sure if we can have an option to use lucky egg in background scan mode, so that trainer can LV up faster, to gain more Lure?

**Comment by HELLspawnTIM** [comment]
PokeAlert is meant to be a scanner/tracking App and not a Bot
If you wish to LevelUp your Accounts faster, use a bot
If you wish to get more Lures, get more Accounts

**Comment by Agilo3** [comment]
Some people have said they actually log into the account manually to place eggs in incubators to hatch eggs (to make the account seem more like real players). You could do the same for activating lucky eggs.

**Comment by edwardwong80** [comment]
Yes I did, but the problem is, PokeAlert will throw away those Lucky Eggs as well, I don't mind to do this myself, if eggs can be kept.

**Comment by PokeAlert** [comment]
Let's not forget PA is not a bot. LVL too fast will make your account ban
