### ISSUE TITLE
Failure to show pokemon

### ISSUE THREAD

**Issue by stekkedecat** [PokeAlert/PokeAlert#444]
I reinstalled Pokealert from scratch today and started with fresh accounts. Everything works exept the pokemon don't show up on the map.
I get the notifications of pokemon (a lot of notifications when all are selected), yet no pokemon are to be found on the map
EDIT1:Pokestops also don't show
EDIT2: debug log file for a single scan extracted and added
[logcat_1484674978061.txt]

**Comment by stekkedecat** [comment]
I don't know what changed, but today it works again...
[logcat_1484721828972.txt](https://github.com/PokeAlert/PokeAlert/files/713170/logcat_1484721828972.txt)

**Comment by PokeAlert** [comment]
On some phone, especially after an update there is a strange issue where pokemon are found but not display on map
