### ISSUE TITLE
Option to have accounts only spin Pokestops to gain pokeballs. 

### ISSUE THREAD

**Issue by thelionroars89** [PokeAlert/PokeAlert#445]
It would be great to have an option where we could send our accounts to spin Pokestops and over lap each other in this kind of scan, so that the accounts can get as many pokestops as possible, so that we can go back to ditto scanning when we live in areas with no pokestops. Please put this in.

**Comment by PokeAlert** [comment]
it is already doing this. Let's not forget pa is not a bot

**Comment by thelionroars89** [comment]
The meaning is to Spin, yet not catch Pokemon, so that you can store them and use them in an area where there is no pokestops.
