### ISSUE TITLE
Won't create accounts

### ISSUE THREAD

**Issue by TheRicktatorship** [PokeAlert/PokeAlert#447]
I cannot create multiple accounts.  When I go to the robot to create accounts it lets me solve one CAPTCHA but it will not let me solve the others.  I says creating account(10 left) and it creates the first one but on the next one it'll say creating account(9 left) and after I solve the CAPTCHA and click continue, it'll say creating account(9 left) and it did that 7 times before I gave up.

I have the Droid Turbo 2, running Android 6.0.1

**Comment by PokeAlert** [comment]
You need a good internet connection. Either way sendme the logs in Discord
