### ISSUE TITLE
Bought Hashkey but Captchas keep on coming!

### ISSUE THREAD

**Issue by happypokemonhunter** [PokeAlert/PokeAlert#449]
I bought a hash key 2 days ago and everything was fine. I could scan with zero problems. Fast forward to this morning and now I am constantly getting captchas and 2 accounts are now banned. Is this happening to anybody else??

**Comment by PokeAlert** [comment]
unfortunately bad timing :)
Nianitc force the API v.51 yersterday. This means keys wont have any effect anymore (it was workind for 2 whole weeks up uptil yersterday)

Don't worry your key will be extanded as soon as they crack the API again :)
