### ISSUE TITLE
map clears when switching app

### ISSUE THREAD

**Issue by Nemo700** [PokeAlert/PokeAlert#45]
Hi and thanks for all your work
Until the last few updates I used to switch between PokeAlert and the game to make sure I was at the right spot or moving in the right direction.
When switching back to PokeAlert the map still showed the pokemons it had found at the previous scan... but since a few days whenever I return to PokeAlert the map is cleared (as if I had pressed the broom button) and I need to rescan to see the pokemons again
Is it normal, is there something to change in the settings or is it a bug ?
Thanks

**Comment by PokeAlert** [comment]
Hey,

I have tried these steps

 1) Start a scan (manual)
 2) couple of pokemon appeared
 3) I stop the scan
 3) I **minimize** the app or switch to an open app
 4) go back in the app
 
I still see all the pokemon.

Is the above steps correct?

**Comment by Nemo700** [comment]
Hi, it's almost the same thing I do, except I don't stop the scan (for example I let the timer on one pokemon that I'm planning to catch), I switch to the game and try to get closer... if he doesn't show up I switch back to pokealert to see if I'm not at the right spot : and the whole map is cleared


----- Mail d'origine -----De: PokeAlert Developers <notifications@github.com>&Agrave;: PokeAlert/PokeAlert <PokeAlert@noreply.github.com>Cc: Nemo700 <nemo700@laposte.net>, Author <author@noreply.github.com>Envoy&eacute;: Wed, 17 Aug 2016 23:47:07 +0200 (CEST)Objet: Re: [PokeAlert/PokeAlert] map clears when switching app (#45)

Hey,
I have tried these steps
1) Start a scan (manual)

2) couple of pokemon appeared

3) I stop the scan

3) I minimize the app or switch to an open app

4) go back in the app
I still see all the pokemon.
Is the above steps correct?
&mdash;You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
