### ISSUE TITLE
chaptchas not showing any more

### ISSUE THREAD

**Issue by RezzZ** [PokeAlert/PokeAlert#450]
It seems (at least for me) that the captchas are no longer showing when trying to solve (as of the app update from yesterday). More people experiencing this?

**Comment by gkgigkgi** [comment]
Yes. It happens to me too. Any suggestion how to fix this?
I tried to restart the app and the device, but not working. Then, uninstalling and reinstalling it, but it also does not fix the issue.

**Comment by tsetset** [comment]
Yup, same here.

**Comment by PokeAlert** [comment]
Yesterday Niantic has serves issue

**Comment by RezzZ** [comment]
this is today... you believe its related to the server errors? so Niantic needs to solve this?

**Comment by tsetset** [comment]
Thanks for the in-app explanation. Looking forward to the update :-)

**Comment by RezzZ** [comment]
for me captcha's are still not working in the app. My first accounts are getting banned now because I cannot solve the captchas...
@PokeAlert, the last update didn't solve this

**Comment by Skronk** [comment]
Please reopen this ticket. I have updated the app, reinstalled it, cleared app data then uninstalled and reinstalled it,  with no success. The app is useless to me until this is fixed, as most of my accounts now require captcha.

**Comment by RezzZ** [comment]
@arhi3a wrote in 452 (which seems lost at, not found):

Q: Why i get white captcha?
A: If you get that white captcha screen, go to playstore and update the "android system webview" app(edited)
That's info from discord FAQ.

This worked for me! so please find android system webview in the playstore and update.
