### ISSUE TITLE
All cache token gone after replacing banned accounts

### ISSUE THREAD

**Issue by edwardwong80** [PokeAlert/PokeAlert#453]
I got 30K+ cache scan token for my account, 2 days ago Niantic introduced new API and caused all my account being banned (or looping in captcha state), so I deleted all accounts and registered new accounts, and I suddenly figure out that my cache scan token = 0 now. Is this intended behaviour?

**Comment by arhi3a** [comment]
Could u go to https://globalpokecache.com and add token and check how many u got. Sometimes PA shows bugged ammount of tokens :D
