### ISSUE TITLE
Got banned...14 out of 23

### ISSUE THREAD

**Issue by linkuphost** [PokeAlert/PokeAlert#459]
Everything was running find before the code changed, all accounts were fine.  Loaded up the new version today and it immediately reported 14 out of 23 were banned.  When I log into the web site, no issues, when trying to log in from Android, it says the PW is bad, then I go to the website and the password is fine.  Change the password, still can't get in.  So what happened?  How to avoid?  Why me?

**Comment by RezzZ** [comment]
I just had 2 of 20 banned. Already had 4 others banned when I couldn't solve the catcha because the captcha was not showing.
Perhaps they also changed the max captcha's per day an account can have before it gets banned?
Not only the max accounts per ip per 10 minutes?

**Comment by xAryaStark** [comment]
There is a ban wave in progress.
