### ISSUE TITLE
Is this the end of PokéAlert?

### ISSUE THREAD

**Issue by lmk3087** [PokeAlert/PokeAlert#467]
Multiple account bans.

When I created new accounts, all they did was trigger captcha  (8, 9 times in a row), never once scanned.

Scans continually crash (quick and background).

When I can get background to run for more than a few seconds, they only find the same one or two pokemon over and over again (5-7 times).

The application is, frankly put, inoperable. I do not know how to begin to list all the issues. Should we expect to have to go back randomly stumbling around hoping to hit something fun because of the new update? Or do you think all these issues can be overcome?

Either way, I appreciate all that you guys have done. Thank you.

**Comment by SephirothAz** [comment]
Hmmm. I use 4.0.13-8 version and it works. New accounts register more and more, all works, all found pokemons normal. Big thanks, my card gives error, when I repair this bug, I donate to you. Open 4.0.13-8 apk, it works good.

**Comment by SephirothAz** [comment]
Yes, I take ban of 10 accounts, but it didn't repeat again, all new accounts works currently and fine.
