### ISSUE TITLE
Pokemon Shuffle Icons instead of those pixelated-blurry ones?

### ISSUE THREAD

**Issue by voythas** [PokeAlert/PokeAlert#47]
Hi, thank you for your hard work! I really appreciate that.
I'd like to ask you for something tho, now in your app you are using some pixelated icons, that gets very blurry and very unreadable for me. I really have to guess what Pokemon is that. May I suggest using or at least giving an option to use Shuffle icons? I even prepared them for different kind of screen densities, here is zip file:
https://dl.dropboxusercontent.com/u/36734285/shuffle_pokemon.zip

I'd be glad. I know it's just a cosmetic thing, but yeah it was bugging me a bit

PS. Each icon is exactly 32dp.

**Comment by TheRadGasm** [comment]
Strongly disagree (sorry!). The original 150 sprites were designed to have clear, distinct, easily-distinguishable silhouettes, while the shuffle sprites are all basically round. When they overlap, you can't tell what you're looking at. 

Plus (admittedly), I really prefer the retro sprites.

**Comment by voythas** [comment]
So as an option, perhaps? And at least lets make them higher res, so they won't be as blurred as they are now?

**Comment by Eric678** [comment]
Can I also vote for higher res icons - the ones used are optimised for desktop resolutions, good quality phones have 5x the pixel resolution and they just look crappy and difficult to differentiate..  Thanks for the good work.

**Comment by PokeAlert** [comment]
Any one know where I can find higher res icon?
(I agree with voythas I don't really like the round ones)

**Comment by disklosr** [comment]
@voythas Could you please reupload the shuffle pictures in a zip file?
Thank you.
