### ISSUE TITLE
[Suggestion] Design overhaul +picture

### ISSUE THREAD

**Issue by voythas** [PokeAlert/PokeAlert#51]
Hey,
While I really love your app, it's so useful, I feel like it could look a bit more organized with hopefully not much work involved.

I prepared a quick mockup for ya:
![pokealert_0](https://cloud.githubusercontent.com/assets/681416/17789078/d770ea26-6590-11e6-9444-c45efd695c72.png)

One screen is using your regular Pokemon icons, but a bit enhanced by me (much sharper etc) and other one is using Shuffle icons that I already suggested in #47. Also, I added "Run in background" as someone mentioned it in #50.

**Comment by PokeAlert** [comment]
Looks awesome :O  !!!

**Comment by voythas** [comment]
Thanks, use it if you wish and if you need anything from me (like icons or whatever) just send me pm.

Also, I made quick mockup for an icon:
![image](https://cloud.githubusercontent.com/assets/681416/17862571/2a1851ee-6896-11e6-96d8-af2fc272a739.png)

Nothing big, just a concept.
