### ISSUE TITLE
Scan time is taking too long.

### ISSUE THREAD

**Issue by LPark205** [PokeAlert/PokeAlert#52]
Version 2.3.7-1 scan time was almost instantaneous and it was great. Now with the new update scan time seems to have reverted back to bring slow. 
Please look into this. I'd like to be able to see Pokemon on the map within the 5 seconds I hit the scan button like it did in ver. 2.3.7-1

**Comment by LPark205** [comment]
The 2.3.8-1 update seems to have fixed the scan time. Works good as new! Thanks PokeAlert!

**Comment by LPark205** [comment]
Scan time became effected again after the latest update.

**Comment by voythas** [comment]
I guess it's because of PokeFast API. In short: there's huge shitstorm about it in reddit. If you turn setting "Use PokeFast" in settings, you will get fast, but probably with fake 'mons.

The easiest way is to add more accounts and you will have fast scan without any limitations.

**Comment by PokeAlert** [comment]
@LPark205 The result you are seeing (very) fast are provided by an external service that uses hundreds of accounts. this services might sometimes go down thus the problem you are seeing.

The owner of the service doesn't like that other people use his service (when he freely uses Niantic sevices for his own good) and doesn't like that PokeAlert has more users than his poorly written app. This is why sometimes you will see these fast pokemon not showing up.

In the latest version (2.3.8-4) you should again see these pokemon. DO not rely to much on these feature. If you feed PokeAlert with 5 or 6 account you can easily finish a 250m scan in couple second.

**Comment by LPark205** [comment]
Ah gotcha. I'll give it a try

**Comment by LPark205** [comment]
So still taking a bit of time to scan. I can only make so many PTC accounts.
