### ISSUE TITLE
eroneous pokemon on alerts

### ISSUE THREAD

**Issue by Num1Phat** [PokeAlert/PokeAlert#55]
Being spammed by false Pokemon; Mew, Moltres, Zapdos, Articuno, Dragonites, Dragonair, Snorlax, etc.....

![app 1](https://cloud.githubusercontent.com/assets/21113958/17795198/50a024e6-6584-11e6-8ae5-6c9d14fe048c.png)

![app 2](https://cloud.githubusercontent.com/assets/21113958/17795186/2e15e960-6584-11e6-8103-83d02a052616.png)
![app 2](https://cloud.githubusercontent.com/assets/21113958/17795187/2f928d16-6584-11e6-8b6f-3ec343588c90.png)
![app 4](https://cloud.githubusercontent.com/assets/21113958/17795189/31ba932c-6584-11e6-96d1-f14342fc1fc9.png)

**Comment by LPark205** [comment]
Omg that's histerical. If only.

**Comment by Num1Phat** [comment]
You're telling me, I was just about to sit down to watch Football, and the Articuno popped up.  I couldn't believe, so I just rushed out the door and headed to it.  On the way there, the Mew popped up right on top of me....  Couldn't believe it.....  Figured it wasn't true, but hey, just in case right.......   LoL, then my phone went banana's with every rare, legendary, epic pokemon just popping up all over the place.  :(

**Comment by doctordo0m** [comment]
Here is the reason, this is only half a bug actually: https://www.google.de/url?sa=t&source=web&rct=j&url=https://m.reddit.com/r/pokemongodev/comments/4yc155/pokealert_is_harming_pokefast_servers/&ved=0ahUKEwiSl4Ke2szOAhUGaRQKHXziAXYQFggbMAA&usg=AFQjCNE553KlBGlZwy6IT5UbacLNyismnA&sig2=5_CmVZ0RsTLkFg9T_yu_ng https://www.google.de/url?sa=t&source=web&rct=j&url=https://m.reddit.com/r/pokemongodev/comments/4yc155/pokealert_is_harming_pokefast_servers/&ved=0ahUKEwiSl4Ke2szOAhUGaRQKHXziAXYQFggbMAA&usg=AFQjCNE553KlBGlZwy6IT5UbacLNyismnA&sig2=5_CmVZ0RsTLkFg9T_yu_ng

**Comment by PokeAlert** [comment]
Fixed in 2.3.8-2
