### ISSUE TITLE
Source code will be released in private repo soon

### ISSUE THREAD

**Issue by PokeAlert** [PokeAlert/PokeAlert#57]
l be handing over the project for 1 week or 2 as I have other stuff to do

**Comment by seikur0** [comment]
Why don't you release the source code right now? You're using the AeonLucid Protos, right? They're licensed under GNU GPLv3, so you're kind of obligated to :P

**Comment by seikur0** [comment]
How is that closed.. I still don't have the source code and you still don't honor the license.
