### ISSUE TITLE
Notification sound

### ISSUE THREAD

**Issue by jrieko** [PokeAlert/PokeAlert#58]
I'd love a setting to choose the notification sound.

I'll gladly knock this one out once the code is public :wink:

**Comment by pokepim** [comment]
Yep, as well as vibration.

BTW the PokeAlert 2.3.8-5 version crashes when I try to activate the background service

**Comment by demolina** [comment]
I also suggested to have the option to wake the screen.
Please, can we have this soon?
I would think this would be a simple implementation. Not sure.

**Comment by jrieko** [comment]
The alternate notification sound is much better, but I meant a user-selected sound. It'd be a super quick change. Check out this [example](http://stackoverflow.com/a/2726008).

**Comment by demolina** [comment]
Yes! User selected sound, please

**Comment by PokeAlert** [comment]
@jrieko @demolina Will be in next update. Sorry about that

**Comment by PokeAlert** [comment]
@jrieko @demolina 
Here you go: 2.3.13-1 with custom sounds
https://github.com/PokeAlert/PokeAlert/releases/tag/2.3.13

**Comment by jrieko** [comment]
![Imgur](http://i.imgur.com/iCJw41H.gif)

Thanks!
