### ISSUE TITLE
There should be an overlay over Pokemon GO

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#62]
The only thing that this app currently needs is the overlay so that we could use the map without minimizing the Pokemon GO (this way we can hatch eggs while looking at map and it is overall more comfortable because sometimes Pokemon GO closes while minimized). There is a code for app floating that may help you to program the overlay: https://github.com/JustinScott/AppFloater/tree/master/AppFloater

**Comment by PokeAlert** [comment]
Hey thanks for this. At the moment I'm cleaning up the code. Refactoring the scan system that will totally improve the speed and stealth of the app.

Once this is done I will start re-working on new feature like the one you proprose

**Comment by shark0der** [comment]
Came here to suggest exactly this. At the moment the only android app with an overlay is livemapgo.tk. Unfortunately it crashes while being in background (I reported this but the dev seems quite busy with other stuff. As a user of an overlay map - going back to non-overlay implementations is painful. This is a must have.

**Comment by Pirulazul** [comment]
While this gets done I use floating windows but overlay is sweet. I also use pokemesh which has overlay support, but PokeAlert is faster when using multiaccount
