### ISSUE TITLE
Low data volume results in non functionality

### ISSUE THREAD

**Issue by insanepowerme** [PokeAlert/PokeAlert#65]
When you run out of high speed internet and go to lower data speed, the app will not show any pokemon anymore. I suspect that it tries to download pokemon sprites but it lacks the speed to do so. 

If this is the case, couldn't we store the sprites on the phone? Overall this would be better for the data usage and make it work with lower speeds aswell

**Comment by PokeAlert** [comment]
Sprites are not downloaded anywhere they are already in the app.
Does PokemonGO works when you lower the data speed?

**Comment by insanepowerme** [comment]
PokemonGO works when lowered, it is slower though and sometimes take a bit of time for the initial loading. But once loaded it works fine.       
         
PokeAlert doesn't work at all. It works when you load it up with wifi and then go outside even with low data speed

**Comment by insanepowerme** [comment]
Can you give me an advice, if your app uses more data if I use more accounts? Does this mean I should use less accounts when I don't want to save data usage. 
Or is this unrelated?

**Comment by PokeAlert** [comment]
The thing that can eat up data is the google map. If you add more account yes it will make more request = more data but requests don't eat THAT much data. Of course if let the app run all day then yes little a little data is accumulated.
