### ISSUE TITLE
Search radius filter not working with fast scan (2.3.8-7)

### ISSUE THREAD

**Issue by Gourdin** [PokeAlert/PokeAlert#66]
Hi here,
Thanks for your app :)

I just intalled last version 2.3.8-7 and got spam with pokemons (accurate spawn, not the problem) from 2km around. 
My search radius is fixed on 210m and have try to change it, not working.
I guess it's linked to Fast Scan, when I desactived it, no more spam and search seems to be alright.

Thanks !

**Comment by PokeAlert** [comment]
Fixed in 2.3.11 and up
