### ISSUE TITLE
[Suggestion] Relocate and shrink UI buttons

### ISSUE THREAD

**Issue by demolina** [PokeAlert/PokeAlert#70]
Nice work with the app, PokeAlert. I love all it can do.

That being said, I think the UI buttons don't need to be that large. If they were the same size as the "ping location" button (upper right corner), that is big enough.

May I suggest to move the buttons below this "ping location" button?
The "enable+disable background service" button below it (to avoid accidental clear presses), and below that the "clear map" button.

The "scan" button can be the bottom center one, if you MUST have one there. That button being the prominent one makes sense to me. Otherwise, the "scan" button would fit nicely below the "clear" button.

As you can see in the screenshot, the way things are right now, there's conflicts with other map buttons. I'm fully aware that only in very special situations this conflict would happen, but it's a conflict none the less.

Edit: there's also a conflict with the "hide Pokemon" (waste basket looking) button.

![screenshot_20160825-121335](https://cloud.githubusercontent.com/assets/20909060/17984067/a0a89190-6ac4-11e6-9490-362c911166b9.png)

![screenshot_20160825-121335 suggestion copy](https://cloud.githubusercontent.com/assets/20909060/17984121/d78f39d4-6ac4-11e6-882f-d2dbe1beb69b.png)

I hope this is an easy implementation, if you decide to follow my suggestion.

Best regards.

**Comment by PokeAlert** [comment]
Hey! you are totally right. 2.3.11-2 fix this

**Comment by demolina** [comment]
Thanks for fixing this.
There's still a conflict with the Pokemon button to the upper left. If you line up the top left with the top right, everything will be fixed.

![screenshot_20160826-125524](https://cloud.githubusercontent.com/assets/20909060/18018707/3b8930a2-6b8d-11e6-9a6a-6e66e7daad12.png)
