### ISSUE TITLE
Battery use is much higher than normal

### ISSUE THREAD

**Issue by demolina** [PokeAlert/PokeAlert#71]
Since version 2.3.11, I've noticed the app is now responsible for 45% of the battery consumption.
It won't even charge the battery while using it plugged in.
Anyone else have this issue?
Version 2.3.11-1 currently in use.

**Comment by PokeAlert** [comment]
hmm, nothing in particular has been changed that can cause this. If you disable the background service does it makes a difference? (It will point me in the right corner of the code)

**Comment by demolina** [comment]
Screenshot to further document the issue
![screenshot_20160825-184802](https://cloud.githubusercontent.com/assets/20909060/17991608/008cb8d6-6af5-11e6-8832-b85c99c34852.png)
Now running version 2.3.11-2 The background scan was disabled and successfully charged around 10% battery in about an hour.

**Comment by demolina** [comment]
I'll enable the scan now and see what happens.

**Comment by demolina** [comment]
It charged normally after that.
I am not sure as to what was happening, but everything is back to normal now.
Thanks for looking into it.
