### ISSUE TITLE
Incorrect release tagged as the latest

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#75]
![incorrect_release](https://cloud.githubusercontent.com/assets/12085708/18026727/4a1f79ec-6c59-11e6-8a06-166a39a7d362.JPG)

**Comment by PokeAlert** [comment]
fixed

**Comment by TFD777** [comment]
@PokeAlert Great, but looks like the previous version apks have disappeared.

**Comment by Paul776** [comment]
Yea I had to remove it. For some reason it kept defaulting on 2.3.10..
I have copy pasted the changes logs into 2.3.11

**Comment by PokeAlert** [comment]
Yea I had to remove it. It kept defaulting to the 2.3.10 for some reason. 
I have copy pasted the changes logs into 2.3.11
