### ISSUE TITLE
There should be an option to set a delay between scans not only scan interval

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#76]
Example: 
Scan interval = 10s
Scan delay / Delay between scans = 2mins

This would scan the map as fast as possible but after scanning the full area the app would wait for 2 minutes before starting another scan. 
Delay could be set from 1min to 10mins (1 minute step). It would help to save battery aswell.

**Comment by PokeAlert** [comment]
+1

**Comment by TFD777** [comment]
@PokeAlert sorry I think I made a mistake. I thought that the Background scan interval will slower the scan if you set more than 10s but looks like it already works as intended just I have noticed that if you set a interval to 1minute and the scan also takes 1 minute to complete then it will immediatelly start to scan without waiting. The solution to that would be starting the Background scan interval timer after the scan finishes because currently it seems that the Background scan interval timer starts in the beginning.
