### ISSUE TITLE
Color circle...

### ISSUE THREAD

**Issue by inu20** [PokeAlert/PokeAlert#79]
There are so many color in the world...
Why you choose those color... >"<

I think you should color each acc with match color.

**Comment by PokeAlert** [comment]
sorry :p I thought it was gonna be more useful. I have put them back as it was before

**Comment by inu20** [comment]
I think the color function of [Flotr2](https://github.com/HumbleSoftware/Flotr2/blob/master/js/Color.js) might help you pick up some nice color. =)

I not really know what different color circle can do, but it maybe useful for you working on it. @v@
