### ISSUE TITLE
Pokemon Filter

### ISSUE THREAD

**Issue by bungral** [PokeAlert/PokeAlert#8]
Hi,

Just wanted to say great work on the app.  Really the best out there at the moment!

However, I can't get the filter to work.  I've taken out all the usual stuff, saved and restarted the notifications and it still picks every last thing up so I get destroyed by notifications.

I've tried restarting the phone also.

Another questions.  Anyone know how many extra accounts it supports?

Cheers.

Edit:  Ok I've been playing around with the settings after another restart and it seems the notifications are behaving themselves but the scan still shows absolutely everything.  Is that expected behaviour?

**Comment by fbreunin** [comment]
Version 2.2.2 is now behaving as expected (filtered out Pokémons also don't appear on the map).

**Comment by bungral** [comment]
Good stuff.  Tested and all good on that front.
