### ISSUE TITLE
Scanning still an issue after upgrading to 2.3.11-5 (Resolved with version 2.3.11-6)

### ISSUE THREAD

**Issue by halloonyc** [PokeAlert/PokeAlert#80]
I have an old S3 with Cyanogenmod 13 (Android version 6.0.1) 
scanning or background scanning stopped working when I upgraded to version 2.3.11-4 and to 2.3.11-5. I downgraded back to 2.3.11-3 and scanning is working again. 

I did a complete uninstall of 2.3.11-3 and installed 2.3.11-5 and scanning still will not work
I cleared the app data and cleared cache and scanning still will not work

version 2.3-11-3 and 2.3.11-2 both worked fine.

**Comment by Pirulazul** [comment]
Same here

**Comment by Pirulazul** [comment]
Solved in 2.3.11-6

**Comment by PokeAlert** [comment]
@Pirulazul @halloonyc I'm aware of -5 not working for everyone one. If you guys are able to I will need you to pull the log cat from your phones.

Also 2.3.12-beta SHOULD fix it.

**Comment by Pirulazul** [comment]
In 2.3.11-6 it worked like a charm, in 2.3.12-beta it keeps working and in 2.3.12 it still works so good job. In case you need logcats just tell me verbose level and I'll send them asap.
