### ISSUE TITLE
Scan skips first couple of requests

### ISSUE THREAD

**Issue by insanepowerme** [PokeAlert/PokeAlert#81]
PokeAlert has a very bad habit of skipping the first set of requests. First set of requests consists of (number of account) x (small circle inside of the large scan radius).            
When you manually scan, the scan will skip the first set. The reason might be that the app has a safety timer before a new request can be made to avoid bans. But it should queue those sets instead of skipping it entirely.          
        
This issue has existed since the beginning of the app iirc.

**Comment by PokeAlert** [comment]
Does it do it the first scan after the app has started? or every first pass no matter when the app had started ?

**Comment by insanepowerme** [comment]
Okay I have just tested it again.          
It doesn't skip when you start and everything is fresh. It doesn't skip if you cancel a previous scan. But it skips if you wait until it is finished with a full scan request and asks for another scan shortly after. You have to wait an invisible timer so it won't skip.

**Comment by PokeAlert** [comment]
Yes I will add a kind of timer between each manual scan
