### ISSUE TITLE
[suggestion] Button to query servers for CP, IVs & movesets of currently selected mon

### ISSUE THREAD

**Issue by Eric678** [PokeAlert/PokeAlert#82]
PoGo API can do it as other apps do - not noticed in scanners yet:  Is it worth going after that mon?

**Comment by PokeAlert** [comment]
I could try adding the CP (iv might requires some extra work though)

**Comment by jnovack** [comment]
CP will be different for different levels (although some levels share with other levels), so that's pointless.

IVs and MoveSets might require capture.  Capturing is "botting" (In the same vein as Murder is different from Trespassing, they are both technically crimes, but one is worse).

**Comment by PokeAlert** [comment]
Sorry didn't had look at how exactly IV & co are calculated. But if it requires capturing and pushing thing to the pogo API PokeAlert wont be doing this.

**Comment by Eric678** [comment]
Yes one would need to enter one's trainer level in settings.  Apparently one can get the rest of the information by just engaging the mon, not actually capturing - there is a MITM module that overlays this information on the screen when you first engage the mon with the standard client. So  no modifications at the server apart from engage and run away - I am not familiar with the API.  Probably would need to be done while you are with the mon in question - so if it is on your notification list pick up the extra info if ticked in settings?  Yes I should just run that module but would prefer not to have to root my phone.  Thanks.
@jnovack I would prefer to be more selective - at a stage where I do not want to accumulate XP, just build my team.
