### ISSUE TITLE
Overlay + background service (not "or") 

### ISSUE THREAD

**Issue by Pirulazul** [PokeAlert/PokeAlert#86]
The only thing remaining for this app to be perfect is enabling overlay and background scan at the same time, right now only one option can be enabled.

**Comment by insanepowerme** [comment]
I also think it has quite some bugs. The overlay breaks the normal app in some cases.

**Comment by PokeAlert** [comment]
For technical reasons I'm disabling the background service when the overlay starts.
Will try to get both working nicely together

**Comment by PokeAlert** [comment]
@insanepowerme When you says break? what do you mean?

**Comment by insanepowerme** [comment]
the real app somehow stops working. you can see the map, you can see notifications i think. but you can't see anything on the map but the buttons and the circle. Nothing else appears (not sure if something still happen) no matter which button you press. Easiest fix is to close and reopen app.

**Comment by PokeAlert** [comment]
If you have step to reproduce it will be cool!

Note also that when you activate the overlay the "real" become obsolete. I disable everything on it (actually I should disable the start button al together)

**Comment by insanepowerme** [comment]
Okay, I misunderstood the intention of the overlay feature. I thought it is an add-on to the regular app and should work together. But if it is meant to be one or the other, it makes sense that it stops working/breaking.               
You can still access the app through android task manager I think.
