### ISSUE TITLE
Release source code?

### ISSUE THREAD

**Issue by compuguy** [PokeAlert/PokeAlert#9]
Will the source code of this app be pushed to this github repository?

**Comment by Deuskull** [comment]
^
Depending on the code, we, dev, can help to improve it.

**Comment by demolina** [comment]
[https://github.com/PokeAlert/PokeAlert/releases](https://github.com/PokeAlert/PokeAlert/releases)
I see some "source code" files at the bottom here.

**Comment by tripleducke** [comment]
@demolina those are empty. Its a zip with a readme anyways.

**Comment by demolina** [comment]
@tripleducke Oh, I had no idea those were empty.

**Comment by compuguy** [comment]
Uh @PokeAlert you didn't fix the issue, you just changed the readme to say "comming soon". I would leave this open until you actually do that....

**Comment by PokeAlert** [comment]
Oops sorry, I have mass closed all the old ticket. But checkout the issue I created today. source code will be released the 29th
