### ISSUE TITLE
[WIP] Overlay map bug fixes

### ISSUE THREAD

**Issue by PokeAlert** [PokeAlert/PokeAlert#91]
So that evreyone is aware i'm writing here the list of todos to fix the current bug related to the new overlay

 - When app is minimised the update send from the service are all lost (pokemon, circles etc..) **[FIXED - 2.3.12-1]**

 - When the app is killed and then tap on a notification not all the pokemon are shown on the map **[FIXED - 2.3.12-1]**

- The background service not running when overlay is active **[FIXED - 2.3.12-1]**

- Disable manual scan when background service is running **[DONE - 2.3.12-1]**

- When a manual scan is running and the user start the overlay the current scan is stopped and all the circles are cleared **[DONE - 2.3.12-1]**

- When there is already pokemon on the main map and the overlay is activated all these pokemon are copied to the overlay map **[DONE - 2.3.12-1]**

- When tap on a notification and overlay is active it should zoom on the overlay **[FIXED - 2.3.12-1]**
(This is a tricky one and can be the cause of potential bugs)

**Comment by PokeAlert** [comment]
https://github.com/PokeAlert/PokeAlert/releases/tag/2.3.12
Released version 2.3.12-1 that fixes all the above points

**Comment by Pirulazul** [comment]
I would add, when background service is enabled and overlay is closed, when you open overlay map,  Pokemons already found are not displayed, only the ones that are found while having overlay map open are shown.
