### ISSUE TITLE
Bugs after update

### ISSUE THREAD

**Issue by emimagnani90** [PokeAlert/PokeAlert#92]
After the last update the app isn't working at all. 

The background service doesn't work anymore, the circles are not moving. 

I receive notifications but these pokemon aren't showing in the map. 

Aparently the service is running much slower(when it works)

**Comment by thiagoafram** [comment]
Ditto. Bg services isn't working. It scans once and that's it. I'll revert back

**Comment by PokeAlert** [comment]
@emimagnani90 Give a go to version 2.3.12-1
