### ISSUE TITLE
High data usage at starts

### ISSUE THREAD

**Issue by aldder** [PokeAlert/PokeAlert#93]
After some tests I notice that at first start of the app it use ~3MB, scans doesn't require more that few KBs. 
If you remove PokeAlert from memory and open it again, it uses again ~3MB. 
Is there a way to prevent this data usage, because in the long run it's a huge cost :D
Last month it took me something like 1.5GB lol
Sorry for bad English

**Comment by PokeAlert** [comment]
Which version are you running ?

**Comment by insanepowerme** [comment]
I suspect that the app emulates the normal pokemon go. so when you start for the first time, it loads every account you have before it starts scanning. This costs a lot of data, I usually try to load the app and the accounts before I leave wifi. 
For the following I don't know if it is still like that in current version: If you don't use the app for a long time, in my experience the accounts somehow log out (maybe unintentionally) and you have to load up all accounts again causing lots of data costs again.        
       
This is what I have experienced but might be technically wrong.

**Comment by aldder** [comment]
I always autoupdate to the latest version, this occurs also in latest 2.3.12-1.

**Anyway i must correct myself.**
This hight data usage occurs when you scan an area NEVER scanned before, since the app is running.

IE:
open the app and scan the actual location (1km) -> 3MBs
move the circle in another location + scan -> 3MBs
move the circle back to the first location + scan -> few KBs

this behavior make me think this is something related to map download

**Comment by PokeAlert** [comment]
Looks to me it's the google map that takes up the data.

this is what happens inside PokeAlert requests side:

1) Start the app for the first time
2) start a scan
3) For each account initialise a login process (which sends between 5 and 10 requests per login)
4) scan starts it will be 1 request per account (+ the response).

5) Stop the scan
6) Start a new scan
7) Check if login? (yes it is for all of them), so no login
8)  scan starts it will be 1 request per account (+ the response).

9) wait 90minute
10) Start a new scan
11)  Check if login? probably not logged, start login process 
12) scan starts it will be 1 request per account (+ the response).
