### ISSUE TITLE
Overlay shutting down the app

### ISSUE THREAD

**Issue by Davcom10** [PokeAlert/PokeAlert#94]
I can't get the overlay to work on my Xiaomi Redmi Note 3 Pro, it just instantly shuts the app down whenever I press the overlay button. I know there is an issue with the MIUI OS where you have to manually accept the permissions for the overlay to work, and I already did that. but it just keeps closing up.

I wonder if there is some kind of problem with my phone or Android version or I'm just doing something wrong.

App Version: 2.3.12-1
Android Version: 5.1.1 LMY47V
MIUI Version: 8.0.1.0 (LHOMIDG)

**Comment by PokeAlert** [comment]
Yesss!!!!!!!!
Finally a Xiaomi user here!

I have soooo much crash reported in the bug reports all Xiaomi users. For some reason when the overlay start it crashes :( for them. impossible to reproduce on my phone.

Would you be ok if send you a special APK  to see where exactly the problem is ?

**Comment by PokeAlert** [comment]
Please come on my Discord channel
https://discord.gg/YeHd9

**Comment by Cyp12die4** [comment]
Hey there, another miui user checking in! 
Overlay mode is crashing for me as well. I am also on miui 8 but i use the global dev version.

If you need another Xiaomi test subject let me now! 
And btw: Awesome Project, thank you!
