### ISSUE TITLE
Option to enable background service is not showing

### ISSUE THREAD

**Issue by lingelbachmb** [PokeAlert/PokeAlert#97]
Phone: Samsung galaxy s6 edge
Android 6.0. 1
App version: 2.3.12-1

My settings only has "Background scan interval"  under Background Service Settings. There isn't another option  for turning on the service. I get no scans unless I do a manual scan. This happens in both the overlay and the main app.

**Comment by PokeAlert** [comment]
The option in the settings has been removed. To enable the background service you need to tap the "bell" icon on the Map screen.

**Comment by lingelbachmb** [comment]
Ah beautiful. Thanks.
