### ISSUE TITLE
Use Fast Scan option?

### ISSUE THREAD

**Issue by halloonyc** [PokeAlert/PokeAlert#98]
What does this option do? Does this mean that the scans I do are sent to a central location where other users of PokeAlert can see the pokemons that I have scanned?

**Comment by PokeAlert** [comment]
it is disabled for now. Discussing with FastPokeMap to possibly use their cache

**Comment by halloonyc** [comment]
Is there a way to Opt out of that when it eventually gets enabled? I feel like using these radars is already tiptoeing violating the games EULA. But scanning and providing the data to a centralized place is definitely going against the EULA.

**Comment by PokeAlert** [comment]
simply turn it off
