### ISSUE TITLE
Background service sometimes stops working 2.3.12-1

### ISSUE THREAD

**Issue by WingChroniam** [PokeAlert/PokeAlert#99]
Occasionally I will find that there are no pokemon appearing at all on the map even though I see it scanning. To make it work again I have to Force Close the App and reopen it. Doing that does the trick, but sometimes I may not notice it stopped and who knows how many Pokemon I missed during that time.

**Comment by PokeAlert** [comment]
Hey! I have rewritten the whole background service to avoid stopping when the phone goes into deep sleep
https://github.com/PokeAlert/PokeAlert/releases/download/2.3.12/PokeAlert_2.3.12-2_beta.apk

Please have a go
